const translations = {
    fr : { 
        credentials: "Identifiants de base de données",
        newcreds: "Nouveaux identifiants",
        back: "Retour",
        help: "Aide",
        menu: "Menu",
        listid: "Liste des identifiants disponibles",
        load: "Chargement des credentials…",
        error: "Réponse inattendue du serveur",
        nocreds: "Aucun credential pour ce projet",
        name: "Nom",
        server: "Serveur",
        database: "Base de données",
        user: "Utilisateur",
        actions: "Actions",
        editcreds: "Éditer ce jeu de credentials",
        delcreds: "Supprimer ce jeu de credentials",
        errorload: "Chargement des credentials :",
        errorreason: "Impossible de charger les credentials",
        checkdel: "Etes-vous sûr de supprimer ces identifiants?",
        delok: "Vos identifiants ont bien été supprimés",
        delko: "Vos identifiants n'ont pas été supprimés",
        addtitle: "Ajout d'identifiants de base de données",
        namelabel: "Nom du jeu (50 cars. max) :",
        serverlabel: "Nom du serveur (250 cars. max) :",
        modelnamelabel: "Nom du modèle :",
        usernamelabel: "Nom de l'utilisateur (50 cars. max) :",
        userpasslabel: "Mot de passe de l'utilisateur (50 cars. max) :",
        validate: "Appliquer",
        close: "Fermer",
        namemandatory: "Le nom du jeu de données est obligatoire",
        recordok: "Vos identifiants de base de données ont bien été enregistrés",
        recordko: "Erreur : vos identifiants de base de données n'ont pas été enregistrés"
    } , 

    en: {
        credentials: "Database credentials",
        newcreds: "New credentials",
        back: "Back",
        close: "Close",
        help: "Help",
        menu: "Menu",
        listid: "Available credentials",
        load: "Loading credentials…",
        error: "Unexpected server response",
        nocreds: "No credentials for this project",
        name: "Name",
        server: "Server",
        database: "Database",
        user: "User",
        actions: "Actions",
        editcreds: "Edit this set of credentials",
        delcreds: "Delete this set of credentials",
        errorload: "Loading credentials:",
        errorreason: "Unable to load credentials",
        checkdel: "Are you sure you want to delete these credentials?",
        delok: "Your credentials have been deleted successfully",
        delko: "Your credentials could not be deleted",
        addtitle: "Add database credentials",
        namelabel: "Set name (max. 50 characters):",
        serverlabel: "Server name (max. 250 characters):",
        modelnamelabel: "Model name:",
        usernamelabel: "Username (max. 50 characters):",
        userpasslabel: "User password (max. 50 characters):",
        validate: "Apply",
        namemandatory: "The credential set name is required",
        recordok: "Your database credentials have been saved successfully",
        recordko: "Error: your database credentials could not be saved"
    },

    it: {
        credentials: "Credenziali del database",
        newcreds: "Nuove credenziali",
        back: "Indietro",
        close: "Chiudi",
        help: "Aiuto",
        menu: "Menu",
        listid: "Elenco delle credenziali disponibili",
        load: "Caricamento delle credenziali…",
        error: "Risposta inattesa dal server",
        nocreds: "Nessuna credenziale per questo progetto",
        name: "Nome",
        server: "Server",
        database: "Database",
        user: "Utente",
        actions: "Azioni",
        editcreds: "Modifica questo insieme di credenziali",
        delcreds: "Elimina questo insieme di credenziali",
        errorload: "Caricamento delle credenziali:",
        errorreason: "Impossibile caricare le credenziali",
        checkdel: "Confermi l'eliminazione di queste credenziali?",
        delok: "Le credenziali sono state eliminate correttamente",
        delko: "Non è stato possibile eliminare le credenziali",
        addtitle: "Aggiungi credenziali del database",
        namelabel: "Nome dell'insieme (max. 50 caratteri):",
        serverlabel: "Nome del server (max. 250 caratteri):",
        modelnamelabel: "Nome del modello:",
        usernamelabel: "Nome utente (max. 50 caratteri):",
        userpasslabel: "Password dell'utente (max. 50 caratteri):",
        validate: "Applica",
        namemandatory: "Il nome dell'insieme di credenziali è obbligatorio",
        recordok: "Le credenziali del database sono state salvate correttamente",
        recordko: "Errore: non è stato possibile salvare le credenziali del database"
    },

    de: {
        credentials: "Datenbankzugangsdaten",
        newcreds: "Neue Zugangsdaten",
        back: "Zurück",
        close: "Schließen",
        help: "Hilfe",
        menu: "Menü",
        listid: "Liste der verfügbaren Zugangsdaten",
        load: "Zugangsdaten werden geladen…",
        error: "Unerwartete Serverantwort",
        nocreds: "Keine Zugangsdaten für dieses Projekt",
        name: "Name",
        server: "Server",
        database: "Datenbank",
        user: "Benutzer",
        actions: "Aktionen",
        editcreds: "Diesen Zugangsdaten-Satz bearbeiten",
        delcreds: "Diesen Zugangsdaten-Satz löschen",
        errorload: "Laden der Zugangsdaten:",
        errorreason: "Zugangsdaten konnten nicht geladen werden",
        checkdel: "Möchten Sie diese Zugangsdaten wirklich löschen?",
        delok: "Ihre Zugangsdaten wurden erfolgreich gelöscht",
        delko: "Ihre Zugangsdaten konnten nicht gelöscht werden",
        addtitle: "Datenbankzugangsdaten hinzufügen",
        namelabel: "Name des Zugangsdaten-Satzes (max. 50 Zeichen):",
        serverlabel: "Servername (max. 250 Zeichen):",
        modelnamelabel: "Modellname:",
        usernamelabel: "Benutzername (max. 50 Zeichen):",
        userpasslabel: "Benutzerpasswort (max. 50 Zeichen):",
        validate: "Übernehmen",
        namemandatory: "Der Name des Zugangsdaten-Satzes ist erforderlich",
        recordok: "Ihre Datenbankzugangsdaten wurden erfolgreich gespeichert",
        recordko: "Fehler: Ihre Datenbankzugangsdaten konnten nicht gespeichert werden"
    },

    es: {
        credentials: "Credenciales de base de datos",
        newcreds: "Nuevas credenciales",
        back: "Volver",
        close: "Cerrar",
        help: "Ayuda",
        menu: "Menú",
        listid: "Lista de credenciales disponibles",
        load: "Cargando credenciales…",
        error: "Respuesta inesperada del servidor",
        nocreds: "No hay credenciales para este proyecto",
        name: "Nombre",
        server: "Servidor",
        database: "Base de datos",
        user: "Usuario",
        actions: "Acciones",
        editcreds: "Editar este conjunto de credenciales",
        delcreds: "Eliminar este conjunto de credenciales",
        errorload: "Carga de credenciales:",
        errorreason: "No se pudieron cargar las credenciales",
        checkdel: "¿Está seguro de que desea eliminar estas credenciales?",
        delok: "Sus credenciales se han eliminado correctamente",
        delko: "No se pudieron eliminar sus credenciales",
        addtitle: "Añadir credenciales de base de datos",
        namelabel: "Nombre del conjunto (máx. 50 caracteres):",
        serverlabel: "Nombre del servidor (máx. 250 caracteres):",
        modelnamelabel: "Nombre del modelo:",
        usernamelabel: "Nombre de usuario (máx. 50 caracteres):",
        userpasslabel: "Contraseña del usuario (máx. 50 caracteres):",
        validate: "Aplicar",
        namemandatory: "El nombre del conjunto de credenciales es obligatorio",
        recordok: "Sus credenciales de base de datos se han guardado correctamente",
        recordko: "Error: no se pudieron guardar sus credenciales de base de datos"
    }
}

renderUI()