const translations = {
    fr : { 
        title: "Beetle studio principale",
        header : "Beetle Studio", 
        disconnect : "Déconnexion", 
        menu : "Menu", 
        help : "Aide", 
        profile : "Profil",
        password: "Mot de passe",
        newproject: "Nouveau projet",
        myprojects: "Mes projets",
        activ: "Activer/Désactiver",
        infos: "Informations",
        proto: "Prototypage",
        delproj: "Supprimer le projet",
        addmember: "Ajouter un membre",
        delmember: "Supprimer un membre",
        alertactiv: "L'activation du projet a bien été effectuée",
        alertdeactiv: "La désactivation du projet a bien été effectuée",
        confirmdelproj: "Dois-je vraiment supprimer ce projet?",
        alertdelproj: "Le projet a été correctement supprimé",
        accountinfos: "Informations du compte",
        details: "Détails",
        addmemberproj: "Ajouter un membre dans un projet",
        memchoice: "Choix d'un membre",
        selectmem: "-- Sélectionner un membre --",
        validate: "Appliquer",
        close: "Fermer",
        alertaddmem: "Sélectionnez le membre que vous souhaitez ajouter",
        alertemailnotsent: "Email non envoyé",
        alertemailsent: "Un mail a été envoyé au nouveau membre",
        delmemberproj: "Supprimer un membre d'un projet",
        newproj: "Créer un nouveau projet",
        yournewproj: "Votre nouveau projet",
        projname: "Nom",
        newprojname: "Nom de votre projet",
        optionaldesc: "Description (optionnel)",
        placeholderdesc: "Donnez une description à votre projet",
        projnamemand: "Le nom de votre nouveau projet est obligatoire",
        alertprojcreated: "Votre projet a bien été créé",
        accountinfosof: "Informations du compte de",
        youraccount: "Votre compte",
        firstname: "Prénom",
        lastname: "Nom",
        email: "Email",
        org: "Organisation",
        orgname: "Nom",
        orgresp: "Responsable",
        project: "Projet",
        projstatus: "Statut",
        projactiv: "Actif",
        projinactiv: "Inactif",
        projdesc: "Description",
        noprojdesc: "Aucune description",
        orgcontact: "Contact",
        orgowner: "Propriétaire",
        projmembers: "Intervenants sur le projet",
        projdetails: "Détails du projet",
        alertdelmem: "Sélectionnez le membre que vous souhaitez retirer du projet",
        alertdelthismem: "Le membre a bien été retiré du projet",
        changepasstitle: "Changer de mot de passe",
        newpassword: "Nouveau mot de passe",
        confirm: "Confirmation",
        placeholderconfirm: "Confirmez votre nouveau mot de passe",
        alertinvalidpass: "Votre nouveau mot de passe n'est pas valide",
        alertinvalidconfirm: "La confirmation ne corresponds pas au nouveau mot de passe",
        alertoldpassused: "Votre nouveau mot de passe est identique à l'ancien",
        alertpasschanged: "Votre mot de passe a bien été modifié"
    } , 

    en : { 
        title: "Beetle Studio main",
        header : "Beetle Studio", 
        disconnect : "Sign out", 
        menu : "Menu", 
        help : "Help", 
        profile : "Profile",
        password: "Password",
        newproject: "New project",
        myprojects: "My projects",
        activ: "Activate/Deactivate",
        infos: "Information",
        proto: "Prototyping",
        delproj: "Delete project",
        addmember: "Add member",
        delmember: "Remove member",
        alertactiv: "Project has been activated",
        alertdeactiv: "Project has been deactivated",
        confirmdelproj: "Do you really want to delete this project?",
        alertdelproj: "Project has been successfully deleted",
        accountinfos: "Account information",
        details: "Details",
        addmemberproj: "Add a member to a project",
        memchoice: "Select a member",
        selectmem: "-- Select a member --",
        validate: "Apply",
        close: "Close",
        alertaddmem: "Please select a member to add",
        alertemailnotsent: "Email not sent",
        alertemailsent: "An email has been sent to the new member",
        delmemberproj: "Remove a member from a project",
        newproj: "Create a new project",
        yournewproj: "Your new project",
        projname: "Name",
        newprojname: "Project name",
        optionaldesc: "Description (optional)",
        placeholderdesc: "Provide a description for your project",
        projnamemand: "Project name is required",
        alertprojcreated: "Your project has been created",
        accountinfosof: "Account information of",
        youraccount: "Your account",
        firstname: "First name",
        lastname: "Last name",
        email: "Email",
        org: "Organization",
        orgname: "Name",
        orgresp: "Manager",
        project: "Project",
        projstatus: "Status",
        projactiv: "Active",
        projinactiv: "Inactive",
        projdesc: "Description",
        noprojdesc: "No description",
        orgcontact: "Contact",
        orgowner: "Owner",
        projmembers: "Project members",
        projdetails: "Project details",
        alertdelmem: "Please select the member you want to remove from the project",
        alertdelthismem: "The member has been successfully removed from the project",
        changepasstitle: "Change password",
        newpassword: "New password",
        confirm: "Confirm",
        placeholderconfirm: "Confirm your new password",
        alertinvalidpass: "Your new password is not valid",
        alertinvalidconfirm: "Confirmation does not match the new password",
        alertoldpassused: "Your new password is the same as the old one",
        alertpasschanged: "Your password has been successfully changed"
    },

    it : {
        title: "Beetle Studio principale",
        header : "Beetle Studio", 
        disconnect : "Disconnettersi", 
        menu : "Menu", 
        help : "Aiuto", 
        profile : "Profilo",
        password: "Password",
        newproject: "Nuovo progetto",
        myprojects: "I miei progetti",
        activ: "Attiva/Disattiva",
        infos: "Informazioni",
        proto: "Prototipazione",
        delproj: "Elimina progetto",
        addmember: "Aggiungi membro",
        delmember: "Rimuovi membro",
        alertactiv: "Progetto attivato",
        alertdeactiv: "Progetto disattivato",
        confirmdelproj: "Vuoi davvero eliminare questo progetto?",
        alertdelproj: "Progetto eliminato correttamente",
        accountinfos: "Informazioni account",
        details: "Dettagli",
        addmemberproj: "Aggiungi un membro al progetto",
        memchoice: "Seleziona un membro",
        selectmem: "-- Seleziona un membro --",
        validate: "Applica",
        close: "Chiudi",
        alertaddmem: "Seleziona un membro da aggiungere",
        alertemailnotsent: "Email non inviata",
        alertemailsent: "Email inviata al nuovo membro",
        delmemberproj: "Rimuovi un membro dal progetto",
        newproj: "Crea un nuovo progetto",
        yournewproj: "Il tuo nuovo progetto",
        projname: "Nome",
        newprojname: "Nome del progetto",
        optionaldesc: "Descrizione (opzionale)",
        placeholderdesc: "Inserisci una descrizione del progetto",
        projnamemand: "Il nome del progetto è obbligatorio",
        alertprojcreated: "Progetto creato con successo",
        accountinfosof: "Informazioni account di",
        youraccount: "Il tuo account",
        firstname: "Nome",
        lastname: "Cognome",
        email: "Email",
        org: "Organizzazione",
        orgname: "Nome",
        orgresp: "Responsabile",
        project: "Progetto",
        projstatus: "Stato",
        projactiv: "Attivo",
        projinactiv: "Inattivo",
        projdesc: "Descrizione",
        noprojdesc: "Nessuna descrizione",
        orgcontact: "Contatto",
        orgowner: "Proprietario",
        projmembers: "Membri del progetto",
        projdetails: "Dettagli del progetto",
        alertdelmem: "Seleziona il membro che desideri rimuovere dal progetto",
        alertdelthismem: "Il membro è stato rimosso dal progetto",
        changepasstitle: "Cambia password",
        newpassword: "Nuova password",
        confirm: "Conferma",
        placeholderconfirm: "Conferma la nuova password",
        alertinvalidpass: "La nuova password non è valida",
        alertinvalidconfirm: "La conferma non corrisponde alla nuova password",
        alertoldpassused: "La nuova password è uguale a quella precedente",
        alertpasschanged: "La password è stata modificata con successo"
    },

    de : {
        title: "Beetle Studio Startseite",
        header : "Beetle Studio", 
        disconnect : "Abmelden", 
        menu : "Menü", 
        help : "Hilfe", 
        profile : "Profil",
        password: "Passwort",
        newproject: "Neues Projekt",
        myprojects: "Meine Projekte",
        activ: "Aktivieren/Deaktivieren",
        infos: "Informationen",
        proto: "Prototyping",
        delproj: "Projekt löschen",
        addmember: "Mitglied hinzufügen",
        delmember: "Mitglied entfernen",
        alertactiv: "Projekt wurde aktiviert",
        alertdeactiv: "Projekt wurde deaktiviert",
        confirmdelproj: "Möchten Sie dieses Projekt wirklich löschen?",
        alertdelproj: "Projekt wurde erfolgreich gelöscht",
        accountinfos: "Kontoinformationen",
        details: "Details",
        addmemberproj: "Mitglied zum Projekt hinzufügen",
        memchoice: "Mitglied auswählen",
        selectmem: "-- Mitglied auswählen --",
        validate: "Anwenden",
        close: "Schließen",
        alertaddmem: "Bitte wählen Sie ein Mitglied aus",
        alertemailnotsent: "E-Mail nicht gesendet",
        alertemailsent: "E-Mail wurde an das neue Mitglied gesendet",
        delmemberproj: "Mitglied aus Projekt entfernen",
        newproj: "Neues Projekt erstellen",
        yournewproj: "Ihr neues Projekt",
        projname: "Name",
        newprojname: "Projektname",
        optionaldesc: "Beschreibung (optional)",
        placeholderdesc: "Geben Sie eine Beschreibung ein",
        projnamemand: "Projektname ist erforderlich",
        alertprojcreated: "Projekt wurde erstellt",
        accountinfosof: "Kontoinformationen von",
        youraccount: "Ihr Konto",
        firstname: "Vorname",
        lastname: "Nachname",
        email: "E-Mail",
        org: "Organisation",
        orgname: "Name",
        orgresp: "Verantwortlicher",
        project: "Projekt",
        projstatus: "Status",
        projactiv: "Aktiv",
        projinactiv: "Inaktiv",
        projdesc: "Beschreibung",
        noprojdesc: "Keine Beschreibung",
        orgcontact: "Kontakt",
        orgowner: "Eigentümer",
        projmembers: "Projektmitglieder",
        projdetails: "Projektdetails",
        alertdelmem: "Bitte wählen Sie das Mitglied aus, das Sie aus dem Projekt entfernen möchten",
        alertdelthismem: "Das Mitglied wurde erfolgreich aus dem Projekt entfernt",
        changepasstitle: "Passwort ändern",
        newpassword: "Neues Passwort",
        confirm: "Bestätigen",
        placeholderconfirm: "Neues Passwort bestätigen",
        alertinvalidpass: "Ihr neues Passwort ist ungültig",
        alertinvalidconfirm: "Die Bestätigung stimmt nicht mit dem neuen Passwort überein",
        alertoldpassused: "Das neue Passwort entspricht dem alten Passwort",
        alertpasschanged: "Ihr Passwort wurde erfolgreich geändert"
    } ,

    es : {
        title: "Beetle Studio principal",
        header : "Beetle Studio", 
        disconnect : "Cerrar sesión", 
        menu : "Menú", 
        help : "Ayuda", 
        profile : "Perfil",
        password: "Contraseña",
        newproject: "Nuevo proyecto",
        myprojects: "Mis proyectos",
        activ: "Activar/Desactivar",
        infos: "Información",
        proto: "Prototipado",
        delproj: "Eliminar proyecto",
        addmember: "Añadir miembro",
        delmember: "Eliminar miembro",
        alertactiv: "El proyecto ha sido activado",
        alertdeactiv: "El proyecto ha sido desactivado",
        confirmdelproj: "¿Deseas eliminar este proyecto?",
        alertdelproj: "El proyecto ha sido eliminado correctamente",
        accountinfos: "Información de la cuenta",
        details: "Detalles",
        addmemberproj: "Añadir miembro al proyecto",
        memchoice: "Seleccionar miembro",
        selectmem: "-- Seleccionar un miembro --",
        validate: "Aplicar",
        close: "Cerrar",
        alertaddmem: "Selecciona un miembro para añadir",
        alertemailnotsent: "Correo no enviado",
        alertemailsent: "Se ha enviado un correo al nuevo miembro",
        delmemberproj: "Eliminar miembro del proyecto",
        newproj: "Crear nuevo proyecto",
        yournewproj: "Tu nuevo proyecto",
        projname: "Nombre",
        newprojname: "Nombre del proyecto",
        optionaldesc: "Descripción (opcional)",
        placeholderdesc: "Añade una descripción al proyecto",
        projnamemand: "El nombre del proyecto es obligatorio",
        alertprojcreated: "El proyecto ha sido creado",
        accountinfosof: "Información de la cuenta de",
        youraccount: "Tu cuenta",
        firstname: "Nombre",
        lastname: "Apellido",
        email: "Correo electrónico",
        org: "Organización",
        orgname: "Nombre",
        orgresp: "Responsable",
        project: "Proyecto",
        projstatus: "Estado",
        projactiv: "Activo",
        projinactiv: "Inactivo",
        projdesc: "Descripción",
        noprojdesc: "Sin descripción",
        orgcontact: "Contacto",
        orgowner: "Propietario",
        projmembers: "Miembros del proyecto",
        projdetails: "Detalles del proyecto",
        alertdelmem: "Selecciona el miembro que deseas eliminar del proyecto",
        alertdelthismem: "El miembro ha sido eliminado del proyecto correctamente",
        changepasstitle: "Cambiar contraseña",
        newpassword: "Nueva contraseña",
        confirm: "Confirmar",
        placeholderconfirm: "Confirma tu nueva contraseña",
        alertinvalidpass: "Tu nueva contraseña no es válida",
        alertinvalidconfirm: "La confirmación no coincide con la nueva contraseña",
        alertoldpassused: "Tu nueva contraseña es igual a la anterior",
        alertpasschanged: "Tu contraseña ha sido cambiada correctamente"
    }
}

renderUI()