const translations = {
    fr : {
        draggable: "Déplacement :",
        dragdefault: "Comportement par défaut",
        drag: "Déplaçable",
        nodrag: "Non déplaçable",

        name: "Nom :", 
        style: "Style en ligne :",
        title: "Beetle Studio prototypage de bases de données",
        proto_header : "Beetle Studio prototypage de bases de données", 
        newworkspace : "Nouvel espace de travail", 
        newcomposant : "Nouveau composant", 
        save : "Sauvegarder", 
        generate : "Génération",
        explorer: "Explorateur",
        palette: "Palette d'outils",
        layout: "Mise en page",
        containers: "Containers",
        simpleobjs: "Objets simples",
        complexobjs: "Composants",
        block: "Division",
        text: "Texte brut",
        span: "Zone de texte",
        label: "Etiquette",
        textfield: "Champ de texte",
        form: "Formulaire",
        img: "Image",
        button: "Bouton",
        anchor: "Ancre",
        li: "Item de liste",
        ul: "Liste non ordonnée",
        ol: "Liste ordonnée",
        htitle: "Titres H1 - H6",
        paragraph: "Paragraphe",
        header: "Entête",
        footer: "Pied",
        article: "Article",
        fieldset: "Groupe d'objets",
        workspace: "Espace de travail",
        trash: "🗑 Glisser ici pour supprimer",
        param: "Paramétrage",
        css: "Styling",
        internflow: "Flux internes",
        model: "Modélisation",
        // pour la popup générique
        apply: "Appliquer",
        close: "Fermer",
        idgen: "Id :",
        stypeclass: "Classe(s) de style :",
        titletitle: "Paramètres du titre",
        sizetitle: "Taille du titre :",
        alertsize: "La taille du titre est obligatoire",
        // pour la popup item de liste
        lititle: "Paramètres de l'item de liste",
        lifor: "Cet item de liste est pour :",
        liforul: "Une liste non ordonnée",
        liforol: "Une liste ordonnée",
        liforval: "Valeur de début :",
        alertval: "Veuillez renseigner la valeur de début",
        // pour la popup anchor
        atitle : "Paramètres de l'ancre",
        aurl: "URL de la page :",
        atarget: "Cible :",
        adefault: "Par défaut",
        ablank: "Nouvelle page vide",
        aparent: "Page parente à la page courante",
        atop: "Première page parente",
        amedia: "Type de média :",
        amediaplaceholder: "Mime type comme 'text/html'",
        acontent: "Contenu :",
        adownload: "Lien de téléchargement",
        alertacontent: "Le contenu de l'ancre est obligatoire",
        // pour la popup button
        buttontitle: "Paramètres du bouton",
        buttoncontent: "Contenu :",
        alertbutton: "Le contenu du bouton est obligatoire",
        // pour la popup text
        texttitle: "Paramètres du texte brut",
        textcontent: "Contenu :",
        // pour la popup span
        spantitle: "Paramètres de la zone de texte",
        // pour la popup zone
        zonetitle: "Paramètres de la zone",
        // pour la popup page
        pagetitle: "Paramètres de la page",
        pagename: "Nom de la page :",
        pagepagettile: "Titre de la page :",
        alertpagename: "Le nom de la page est obligatoire",
        // pour la popup image
        imgtitle: "Paramètres de l'image",
        imgsource: "Source :",
        // pour la popup division
        blocktitle: "Paramètres de la division",
        // pour la popup etiquette
        labeltitle: "Paramètres de l'étiquette",
        labelfor: "Label pour :",
        // pour la popup textfield
        tftitle: "Paramètres du champ de texte",
        tftype: "Type :",
        tftype1: "Texte",
        tftype2: "Mot de passe",
        tftype3: "Fichier",
        tftype4: "Bouton",
        tftype5: "Couleur",
        tftype6: "Date",
        tftype7: "Date locale",
        tftype8: "Email",
        tftype9: "Non visible",
        tftype10: "Case à cocher",
        tftype11: "Image",
        tftype12: "Mois",
        tftype13: "Nombre",
        tftype14: "Radio",
        tftype15: "Intervalle",
        tftype16: "Réinitialisation",
        tftype17: "Recherche",
        tftype18: "Soumettre",
        tftype19: "Numéro de téléphone",
        tftype20: "Heure",
        tftype21: "Url",
        tfinitialval: "Valeur initiale :",
        tfplaceholder: "Contenu fictif :",
        tfdisabled: "Indisponible",
        tfreadonly: "Lecture seule",
        tfrequired: "Obligatoire",
        tfmin: "Minimum :",
        tfmax: "Maximum :",
        tfstep: "Pas :",
        tfcheck: "Case cochée",
        tflongmax: "Longueur maximale :",
        // pour la popup form
        formtitle: "Paramètres du formulaire",
        formid: "Id :",
        formname: "Nom :",
        formmethod: "Methode :",
        formpost: "Données cachées (POST)",
        formget: "Données passées dans l'url (GET)",
        formtarget: "Cible :",
        formself: "La page courante par défaut",
        formblank: "Page vide",
        formparent: "Page parente",
        formtop: "Première page",
        formenc: "Type d'encodage :",
        formencdef: "Type d'encodage par défaut",
        formencfile: "Type d'encodage pour les textfields de type 'fichier'",
        formencplain: "Type d'encodage pour le débuggage",
        formnoval: "Empêcher la validation du formulaire"
    } , 
    en : { 
    },
    it : { 
    },
    de : { 
    },
    es : { 
    }
}

renderUI()