const translations = {
    fr : { 
        title: "Beetle Studio : Modèle de données",
        back : "Retour", 
        menu : "Menu", 
        help : "Aide", 
        profile : "Profil",
        newmodel: "Nouveau modèle",
        model: "Aller sur le modèle de données",
        mymodels: "Mes modèles de données",
        editmodel: "Editer les informations du modèle",
        delmodel: "Supprimer le modèle",
        validate: "Appliquer",
        close: "Fermer",
        newmodeltitle: "Création d'un nouveau modèle",
        namelabel: "Nom du modèle (50 car. max) :",
        descriptionlabel: "Description (250 car. max) :",
        setlabel: "Jeu d'identifiants :",
        saveerror: "Le nom de votre nouveau modèle est obligatoire",
        saveok: "Votre modèle a bien été modifié",
        saveko: "Erreur : votre modèle n'a pas été modifié",
        createok: "Votre nouveau modèle a bien été créé",
        createko: "Erreur : votre nouveau modèle n'a pas été créé",
        delanswer: "Souhaitez-vous vraiment supprimer ce modèle?",
        delok: "Votre modèle a bien été supprimé",
        delko: "Erreur : votre modèle n'a pas été supprimé"
    } , 

    en: {
        title: "Beetle Studio: Data model",
        back: "Back",
        menu: "Menu",
        help: "Help",
        profile: "Profile",
        newmodel: "New model",
        model: "Open the data model",
        mymodels: "My data models",
        editmodel: "Edit model information",
        delmodel: "Delete the model",
        validate: "Apply",
        close: "Close",
        newmodeltitle: "Create a new model",
        namelabel: "Model name (max. 50 characters):",
        descriptionlabel: "Description (max. 250 characters):",
        setlabel: "Credential set:",
        saveerror: "The name of your new model is required",
        saveok: "Your model has been updated successfully",
        saveko: "Error: your model could not be updated",
        createok: "Your new model has been created successfully",
        createko: "Error: your new model could not be created",
        delanswer: "Are you sure you want to delete this model?",
        delok: "Your model has been deleted successfully",
        delko: "Error: your model could not be deleted"
    },

    it: {
        title: "Beetle Studio: Modello di dati",
        back: "Indietro",
        menu: "Menu",
        help: "Aiuto",
        profile: "Profilo",
        newmodel: "Nuovo modello",
        model: "Apri il modello di dati",
        mymodels: "I miei modelli di dati",
        editmodel: "Modifica le informazioni del modello",
        delmodel: "Elimina il modello",
        validate: "Applica",
        close: "Chiudi",
        newmodeltitle: "Crea un nuovo modello",
        namelabel: "Nome del modello (max. 50 caratteri):",
        descriptionlabel: "Descrizione (max. 250 caratteri):",
        setlabel: "Insieme di credenziali:",
        saveerror: "Il nome del nuovo modello è obbligatorio",
        saveok: "Il modello è stato modificato correttamente",
        saveko: "Errore: non è stato possibile modificare il modello",
        createok: "Il nuovo modello è stato creato correttamente",
        createko: "Errore: non è stato possibile creare il nuovo modello",
        delanswer: "Confermi l'eliminazione di questo modello?",
        delok: "Il modello è stato eliminato correttamente",
        delko: "Errore: non è stato possibile eliminare il modello"
    },

    de: {
        title: "Beetle Studio: Datenmodell",
        back: "Zurück",
        menu: "Menü",
        help: "Hilfe",
        profile: "Profil",
        newmodel: "Neues Modell",
        model: "Datenmodell öffnen",
        mymodels: "Meine Datenmodelle",
        editmodel: "Modellinformationen bearbeiten",
        delmodel: "Modell löschen",
        validate: "Übernehmen",
        close: "Schließen",
        newmodeltitle: "Neues Modell erstellen",
        namelabel: "Modellname (max. 50 Zeichen):",
        descriptionlabel: "Beschreibung (max. 250 Zeichen):",
        setlabel: "Zugangsdaten-Satz:",
        saveerror: "Der Name Ihres neuen Modells ist erforderlich",
        saveok: "Ihr Modell wurde erfolgreich geändert",
        saveko: "Fehler: Ihr Modell konnte nicht geändert werden",
        createok: "Ihr neues Modell wurde erfolgreich erstellt",
        createko: "Fehler: Ihr neues Modell konnte nicht erstellt werden",
        delanswer: "Möchten Sie dieses Modell wirklich löschen?",
        delok: "Ihr Modell wurde erfolgreich gelöscht",
        delko: "Fehler: Ihr Modell konnte nicht gelöscht werden"
    },

    es: {
        title: "Beetle Studio: Modelo de datos",
        back: "Volver",
        menu: "Menú",
        help: "Ayuda",
        profile: "Perfil",
        newmodel: "Nuevo modelo",
        model: "Abrir el modelo de datos",
        mymodels: "Mis modelos de datos",
        editmodel: "Editar la información del modelo",
        delmodel: "Eliminar el modelo",
        validate: "Aplicar",
        close: "Cerrar",
        newmodeltitle: "Crear un nuevo modelo",
        namelabel: "Nombre del modelo (máx. 50 caracteres):",
        descriptionlabel: "Descripción (máx. 250 caracteres):",
        setlabel: "Conjunto de credenciales:",
        saveerror: "El nombre del nuevo modelo es obligatorio",
        saveok: "Su modelo se ha modificado correctamente",
        saveko: "Error: no se pudo modificar su modelo",
        createok: "Su nuevo modelo se ha creado correctamente",
        createko: "Error: no se pudo crear su nuevo modelo",
        delanswer: "¿Está seguro de que desea eliminar este modelo?",
        delok: "Su modelo se ha eliminado correctamente",
        delko: "Error: no se pudo eliminar su modelo"
    }
}

renderUI()