const translations = {
    fr : { 
        title: "Beetle Studio Prototype",
        proto_header : "Beetle Studio - Prototypage", 
        newworkspace : "Nouvel espace de travail", 
        newcomposant : "Nouveau composant", 
        save : "Sauvegarder", 
        explorer: "Explorateur",
        palette: "Palette d'outils",
        layout: "Mise en page",
        containers: "Containers",
        simpleobjs: "Objets simples",
        complexobjs: "Composants",
        layout1z: "Mise en page 1 zone",
        layout2z: "Mise en page 2 zones",
        layout3z: "Mise en page 3 zones",
        layout4z: "Mise en page 4 zones",
        layout5z: "Mise en page 5 zones",
        block: "Division",
        text: "Texte brut",
        span: "Zone de texte",
        label: "Etiquette",
        textfield: "Champ de texte",
        form: "Formulaire",
        img: "Image",
        button: "Bouton",
        anchor: "Ancre",
        li: "Item de liste",
        ul: "Liste non ordonnée",
        ol: "Liste ordonnée",
        htitle: "Titres H1 - H6",
        paragraph: "Paragraphe",
        header: "Entête",
        footer: "Pied",
        article: "Article",
        fieldset: "Groupe d'objets",
        workspace: "Espace de travail",
        trash: "🗑 Glisser ici pour supprimer",
        param: "Paramétrage",
        css: "Styling",
        internflow: "Flux internes",
        model: "Modélisation",
        // pour la popup générique
        apply: "Appliquer",
        close: "Fermer",
        idgen: "Id :",
        stypeclass: "Classe(s) de style :",
        titletitle: "Paramètres du titre",
        sizetitle: "Taille du titre :",
        alertsize: "La taille du titre est obligatoire",
        // pour la popup item de liste
        lititle: "Paramètres de l'item de liste",
        lifor: "Cet item de liste est pour :",
        liforul: "Une liste non ordonnée",
        liforol: "Une liste ordonnée",
        liforval: "Valeur de début :",
        alertval: "Veuillez renseigner la valeur de début",
        // pour la popup anchor
        atitle : "Paramètres de l'ancre",
        aurl: "URL de la page :",
        atarget: "Cible :",
        adefault: "Par défaut",
        ablank: "Nouvelle page vide",
        aparent: "Page parente à la page courante",
        atop: "Première page parente",
        amedia: "Type de média :",
        amediaplaceholder: "Mime type comme 'text/html'",
        acontent: "Contenu :",
        adownload: "Lien de téléchargement",
        alertacontent: "Le contenu de l'ancre est obligatoire",
        // pour la popup button
        buttontitle: "Paramètres du bouton",
        buttoncontent: "Contenu :",
        alertbutton: "Le contenu du bouton est obligatoire",
        // pour la popup text
        texttitle: "Paramètres du texte brut",
        textcontent: "Contenu :",
        // pour la popup span
        spantitle: "Paramètres de la zone de texte",
        spancontent: "Contenu :",
        // pour la popup mise en page
        layouttitle: "Paramètres de la mise en page",
        layoutzonecount: "Nombre de zones :",
        // pour la popup zone
        zonetitle: "Paramètres de la zone",
        // pour la popup page
        pagetitle: "Paramètres de la page",
        pagename: "Nom de la page :",
        pagepagettile: "Titre de la page :",
        alertpagename: "Le nom de la page est obligatoire",
        // pour la popup image
        imgtitle: "Paramètres de l'image",
        imgstyle: "Style en ligne :",
        imgsource: "Source :",
        // pour la popup division
        blocktitle: "Paramètres de l'image",
        blockstyle: "Style en ligne :",
        // pour la popup etiquette
        labeltitle: "Paramètres de l'étiquette",
        labelfor: "Label pour :",
        labelstyle: "Style en ligne :",
        // pour la popup textfield
        tftitle: "Paramètres du champ de texte",
        tfname: "Nom :",
        tftype: "Type :",
        tftype1: "Texte",
        tftype2: "Mot de passe",
        tftype3: "Fichier",
        tftype4: "Bouton",
        tftype5: "Couleur",
        tftype6: "Date",
        tftype7: "Date locale",
        tftype8: "Email",
        tftype9: "Non visible",
        tftype10: "Case à cocher",
        tftype11: "Image",
        tftype12: "Mois",
        tftype13: "Nombre",
        tftype14: "Radio",
        tftype15: "Intervalle",
        tftype16: "Réinitialisation",
        tftype17: "Recherche",
        tftype18: "Soumettre",
        tftype19: "Numéro de téléphone",
        tftype20: "Heure",
        tftype21: "Url",
        tfinitialval: "Initial value :",
        tfstyle: "Style en ligne :",
        tfplaceholder: "Contenu fictif :",
        tfdisabled: "Indisponible",
        tfreadonly: "Lecture seule",
        tfrequired: "Obligatoire",
        tfmin: "Minimum :",
        tfmax: "Maximum :",
        tfstep: "Pas :",
        tfcheck: "Case cochée",
        tflongmax: "Longueur maximale :",
        // pour la popup form
        formtitle: "Paramètres du formulaire",
        formid: "Id :",
        formname: "Nom :",
        formmethod: "Methode :",
        formpost: "Données cachées (POST)",
        formget: "Données passées dans l'url (GET)",
        formtarget: "Cible :",
        formself: "La page courante par défaut",
        formblank: "Page vide",
        formparent: "Page parente",
        formtop: "Première page",
        formenc: "Type d'encodage :",
        formencdef: "Type d'encodage par défaut",
        formencfile: "Type d'encodage pour les textfields de type 'fichier'",
        formencplain: "Type d'encodage pour le débuggage",
        formnoval: "Empêcher la validation du formulaire"
    } , 
    en : { 
        title: "Beetle Studio Prototype",
        proto_header : "Beetle Studio - Prototyping", 
        newworkspace : "New workspace", 
        newcomposant : "New component", 
        save : "Save", 
        explorer: "Explorer",
        palette: "Tool palette",
        layout: "Layout",
        containers: "Containers",
        simpleobjs: "Simple objects",
        complexobjs: "Components",
        layout1z: "1-zone layout",
        layout2z: "2-zone layout",
        layout3z: "3-zone layout",
        layout4z: "4-zone layout",
        layout5z: "5-zone layout",
        block: "Container",
        text: "Raw text",
        span: "Text span",
        label: "Label",
        textfield: "Text field",
        form: "Form",
        img: "Image",
        button: "Button",
        anchor: "Link",
        li: "List item",
        ul: "Unordered list",
        ol: "Ordered list",
        htitle: "Headings H1 - H6",
        paragraph: "Paragraph",
        header: "Header",
        footer: "Footer",
        article: "Article",
        fieldset: "Field group",
        workspace: "Workspace",
        trash: "🗑 Drag here to delete",
        param: "Settings",
        css: "Styling",
        internflow: "Internal flows",
        model: "Modeling",
        apply: "Apply",
        close: "Close",
        idgen: "Id:",
        stypeclass: "Style class(es):",
        titletitle: "Title settings",
        sizetitle: "Title size:",
        alertsize: "Title size is required",

        lititle: "List item settings",
        lifor: "This item is for:",
        liforul: "Unordered list",
        liforol: "Ordered list",
        liforval: "Start value:",
        alertval: "Please enter a start value",

        atitle : "Link settings",
        aurl: "Page URL:",
        atarget: "Target:",
        adefault: "Default",
        ablank: "New blank page",
        aparent: "Parent page",
        atop: "Top parent page",
        amedia: "Media type:",
        amediaplaceholder: "Mime type like 'text/html'",
        acontent: "Content:",
        adownload: "Download link",
        alertacontent: "Link content is required",

        buttontitle: "Button settings",
        buttoncontent: "Content:",
        alertbutton: "Button content is required",

        texttitle: "Raw text settings",
        textcontent: "Content:",

        spantitle: "Text span settings",
        spancontent: "Content:",

        layouttitle: "Layout settings",
        layoutzonecount: "Number of zones:",

        zonetitle: "Zone settings",

        pagetitle: "Page settings",
        pagename: "Page name:",
        pagepagettile: "Page title:",
        alertpagename: "Page name is required",

        imgtitle: "Image settings",
        imgstyle: "Inline style:",
        imgsource: "Source:",

        blocktitle: "Container settings",
        blockstyle: "Inline style:",

        labeltitle: "Label settings",
        labelfor: "Label for:",
        labelstyle: "Inline style:",

        tftitle: "Text field settings",
        tfname: "Name:",
        tftype: "Type:",
        tftype1: "Text",
        tftype2: "Password",
        tftype3: "File",
        tftype4: "Button",
        tftype5: "Color",
        tftype6: "Date",
        tftype7: "Local date",
        tftype8: "Email",
        tftype9: "Hidden",
        tftype10: "Checkbox",
        tftype11: "Image",
        tftype12: "Month",
        tftype13: "Number",
        tftype14: "Radio",
        tftype15: "Range",
        tftype16: "Reset",
        tftype17: "Search",
        tftype18: "Submit",
        tftype19: "Phone",
        tftype20: "Time",
        tftype21: "URL",
        tfinitialval: "Initial value:",
        tfstyle: "Inline style:",
        tfplaceholder: "Placeholder:",
        tfdisabled: "Disabled",
        tfreadonly: "Read only",
        tfrequired: "Required",
        tfmin: "Minimum:",
        tfmax: "Maximum:",
        tfstep: "Step:",
        tfcheck: "Checked",
        tflongmax: "Max length:",

        formtitle: "Form settings",
        formid: "Id:",
        formname: "Name:",
        formmethod: "Method:",
        formpost: "Hidden data (POST)",
        formget: "URL data (GET)",
        formtarget: "Target:",
        formself: "Current page",
        formblank: "Blank page",
        formparent: "Parent page",
        formtop: "Top page",
        formenc: "Encoding type:",
        formencdef: "Default encoding",
        formencfile: "File upload encoding",
        formencplain: "Debug encoding",
        formnoval: "Disable validation"
    },
    it : { 
        title: "Beetle Studio Prototipo",
        proto_header : "Beetle Studio - Prototipazione", 
        newworkspace : "Nuovo spazio di lavoro", 
        newcomposant : "Nuovo componente", 
        save : "Salva", 
        explorer: "Esploratore",
        palette: "Palette strumenti",
        layout: "Layout",
        containers: "Contenitori",
        simpleobjs: "Oggetti semplici",
        complexobjs: "Componenti",
        layout1z: "Layout 1 zona",
        layout2z: "Layout 2 zone",
        layout3z: "Layout 3 zone",
        layout4z: "Layout 4 zone",
        layout5z: "Layout 5 zone",
        block: "Divisione",
        text: "Testo semplice",
        span: "Area di testo",
        label: "Etichetta",
        textfield: "Campo di testo",
        form: "Modulo",
        img: "Immagine",
        button: "Pulsante",
        anchor: "Link",
        li: "Elemento lista",
        ul: "Lista non ordinata",
        ol: "Lista ordinata",
        htitle: "Titoli H1 - H6",
        paragraph: "Paragrafo",
        header: "Intestazione",
        footer: "Piè di pagina",
        article: "Articolo",
        fieldset: "Gruppo di campi",
        workspace: "Spazio di lavoro",
        trash: "🗑 Trascina qui per eliminare",
        param: "Parametri",
        css: "Stile",
        internflow: "Flussi interni",
        model: "Modellazione",

        apply: "Applica",
        close: "Chiudi",
        idgen: "Id:",
        stypeclass: "Classe/i di stile:",
        titletitle: "Parametri del titolo",
        sizetitle: "Dimensione del titolo:",
        alertsize: "La dimensione del titolo è obbligatoria",

        lititle: "Parametri dell'elemento lista",
        lifor: "Questo elemento è per:",
        liforul: "Lista non ordinata",
        liforol: "Lista ordinata",
        liforval: "Valore iniziale:",
        alertval: "Inserire il valore iniziale",

        atitle : "Parametri del link",
        aurl: "URL della pagina:",
        atarget: "Destinazione:",
        adefault: "Predefinito",
        ablank: "Nuova pagina vuota",
        aparent: "Pagina padre",
        atop: "Pagina principale",
        amedia: "Tipo di media:",
        amediaplaceholder: "Mime type come 'text/html'",
        acontent: "Contenuto:",
        adownload: "Link di download",
        alertacontent: "Il contenuto del link è obbligatorio",

        buttontitle: "Parametri del pulsante",
        buttoncontent: "Contenuto:",
        alertbutton: "Il contenuto del pulsante è obbligatorio",

        texttitle: "Parametri del testo",
        textcontent: "Contenuto:",

        spantitle: "Parametri dell'area di testo",
        spancontent: "Contenuto:",

        layouttitle: "Parametri del layout",
        layoutzonecount: "Numero di zone:",

        zonetitle: "Parametri della zona",

        pagetitle: "Parametri della pagina",
        pagename: "Nome della pagina:",
        pagepagettile: "Titolo della pagina:",
        alertpagename: "Il nome della pagina è obbligatorio",

        imgtitle: "Parametri dell'immagine",
        imgstyle: "Stile inline:",
        imgsource: "Sorgente:",

        blocktitle: "Parametri della divisione",
        blockstyle: "Stile inline:",

        labeltitle: "Parametri dell'etichetta",
        labelfor: "Etichetta per:",
        labelstyle: "Stile inline:",

        tftitle: "Parametri del campo di testo",
        tfname: "Nome:",
        tftype: "Tipo:",
        tftype1: "Testo",
        tftype2: "Password",
        tftype3: "File",
        tftype4: "Pulsante",
        tftype5: "Colore",
        tftype6: "Data",
        tftype7: "Data locale",
        tftype8: "Email",
        tftype9: "Nascosto",
        tftype10: "Checkbox",
        tftype11: "Immagine",
        tftype12: "Mese",
        tftype13: "Numero",
        tftype14: "Radio",
        tftype15: "Intervallo",
        tftype16: "Reset",
        tftype17: "Ricerca",
        tftype18: "Invio",
        tftype19: "Telefono",
        tftype20: "Ora",
        tftype21: "URL",
        tfinitialval: "Valore iniziale:",
        tfstyle: "Stile inline:",
        tfplaceholder: "Segnaposto:",
        tfdisabled: "Disabilitato",
        tfreadonly: "Sola lettura",
        tfrequired: "Obbligatorio",
        tfmin: "Minimo:",
        tfmax: "Massimo:",
        tfstep: "Passo:",
        tfcheck: "Selezionato",
        tflongmax: "Lunghezza massima:",

        formtitle: "Parametri del modulo",
        formid: "Id:",
        formname: "Nome:",
        formmethod: "Metodo:",
        formpost: "Dati nascosti (POST)",
        formget: "Dati nell'URL (GET)",
        formtarget: "Destinazione:",
        formself: "Pagina corrente",
        formblank: "Pagina vuota",
        formparent: "Pagina padre",
        formtop: "Pagina principale",
        formenc: "Tipo di codifica:",
        formencdef: "Codifica predefinita",
        formencfile: "Codifica per file",
        formencplain: "Codifica per debug",
        formnoval: "Disabilita la validazione"
    },
    de : { 
        title: "Beetle Studio Prototyp",
        proto_header : "Beetle Studio - Prototyping", 
        newworkspace : "Neuer Arbeitsbereich", 
        newcomposant : "Neue Komponente", 
        save : "Speichern", 
        explorer: "Explorer",
        palette: "Werkzeugpalette",
        layout: "Layout",
        containers: "Container",
        simpleobjs: "Einfache Objekte",
        complexobjs: "Komponenten",
        layout1z: "Layout mit 1 Bereich",
        layout2z: "Layout mit 2 Bereichen",
        layout3z: "Layout mit 3 Bereichen",
        layout4z: "Layout mit 4 Bereichen",
        layout5z: "Layout mit 5 Bereichen",
        block: "Bereich",
        text: "Reiner Text",
        span: "Textbereich",
        label: "Beschriftung",
        textfield: "Textfeld",
        form: "Formular",
        img: "Bild",
        button: "Button",
        anchor: "Link",
        li: "Listenelement",
        ul: "Ungeordnete Liste",
        ol: "Geordnete Liste",
        htitle: "Überschriften H1 - H6",
        paragraph: "Absatz",
        header: "Kopfbereich",
        footer: "Fußbereich",
        article: "Artikel",
        fieldset: "Feldgruppe",
        workspace: "Arbeitsbereich",
        trash: "🗑 Hierher ziehen zum Löschen",
        param: "Parameter",
        css: "Styling",
        internflow: "Interne Abläufe",
        model: "Modellierung",

        apply: "Anwenden",
        close: "Schließen",
        idgen: "Id:",
        stypeclass: "Style-Klasse(n):",
        titletitle: "Titel-Einstellungen",
        sizetitle: "Titelgröße:",
        alertsize: "Die Titelgröße ist erforderlich",

        lititle: "Einstellungen für Listenelement",
        lifor: "Dieses Element ist für:",
        liforul: "Ungeordnete Liste",
        liforol: "Geordnete Liste",
        liforval: "Startwert:",
        alertval: "Bitte einen Startwert eingeben",

        atitle : "Link-Einstellungen",
        aurl: "Seiten-URL:",
        atarget: "Ziel:",
        adefault: "Standard",
        ablank: "Neue leere Seite",
        aparent: "Übergeordnete Seite",
        atop: "Oberste Seite",
        amedia: "Medientyp:",
        amediaplaceholder: "Mime-Typ wie 'text/html'",
        acontent: "Inhalt:",
        adownload: "Download-Link",
        alertacontent: "Der Inhalt des Links ist erforderlich",

        buttontitle: "Button-Einstellungen",
        buttoncontent: "Inhalt:",
        alertbutton: "Der Button-Inhalt ist erforderlich",

        texttitle: "Text-Einstellungen",
        textcontent: "Inhalt:",

        spantitle: "Textbereich-Einstellungen",
        spancontent: "Inhalt:",

        layouttitle: "Layout-Einstellungen",
        layoutzonecount: "Anzahl der Bereiche:",

        zonetitle: "Bereich-Einstellungen",

        pagetitle: "Seiten-Einstellungen",
        pagename: "Seitenname:",
        pagepagettile: "Seitentitel:",
        alertpagename: "Der Seitenname ist erforderlich",

        imgtitle: "Bild-Einstellungen",
        imgstyle: "Inline-Stil:",
        imgsource: "Quelle:",

        blocktitle: "Bereich-Einstellungen",
        blockstyle: "Inline-Stil:",

        labeltitle: "Beschriftungs-Einstellungen",
        labelfor: "Beschriftung für:",
        labelstyle: "Inline-Stil:",

        tftitle: "Textfeld-Einstellungen",
        tfname: "Name:",
        tftype: "Typ:",
        tftype1: "Text",
        tftype2: "Passwort",
        tftype3: "Datei",
        tftype4: "Button",
        tftype5: "Farbe",
        tftype6: "Datum",
        tftype7: "Lokales Datum",
        tftype8: "E-Mail",
        tftype9: "Versteckt",
        tftype10: "Checkbox",
        tftype11: "Bild",
        tftype12: "Monat",
        tftype13: "Zahl",
        tftype14: "Radio",
        tftype15: "Bereich",
        tftype16: "Zurücksetzen",
        tftype17: "Suche",
        tftype18: "Absenden",
        tftype19: "Telefon",
        tftype20: "Zeit",
        tftype21: "URL",
        tfinitialval: "Anfangswert:",
        tfstyle: "Inline-Stil:",
        tfplaceholder: "Platzhalter:",
        tfdisabled: "Deaktiviert",
        tfreadonly: "Nur lesen",
        tfrequired: "Erforderlich",
        tfmin: "Minimum:",
        tfmax: "Maximum:",
        tfstep: "Schritt:",
        tfcheck: "Ausgewählt",
        tflongmax: "Maximale Länge:",

        formtitle: "Formular-Einstellungen",
        formid: "Id:",
        formname: "Name:",
        formmethod: "Methode:",
        formpost: "Versteckte Daten (POST)",
        formget: "Daten in der URL (GET)",
        formtarget: "Ziel:",
        formself: "Aktuelle Seite",
        formblank: "Leere Seite",
        formparent: "Übergeordnete Seite",
        formtop: "Oberste Seite",
        formenc: "Kodierungstyp:",
        formencdef: "Standardkodierung",
        formencfile: "Kodierung für Dateien",
        formencplain: "Kodierung für Debugging",
        formnoval: "Validierung deaktivieren"
    },
    es : { 
        title: "Beetle Studio Prototipo",
        proto_header : "Beetle Studio - Prototipado", 
        newworkspace : "Nuevo espacio de trabajo", 
        newcomposant : "Nuevo componente", 
        save : "Guardar", 
        explorer: "Explorador",
        palette: "Paleta de herramientas",
        layout: "Diseño",
        containers: "Contenedores",
        simpleobjs: "Objetos simples",
        complexobjs: "Componentes",
        layout1z: "Diseño de 1 zona",
        layout2z: "Diseño de 2 zonas",
        layout3z: "Diseño de 3 zonas",
        layout4z: "Diseño de 4 zonas",
        layout5z: "Diseño de 5 zonas",
        block: "División",
        text: "Texto simple",
        span: "Área de texto",
        label: "Etiqueta",
        textfield: "Campo de texto",
        form: "Formulario",
        img: "Imagen",
        button: "Botón",
        anchor: "Enlace",
        li: "Elemento de lista",
        ul: "Lista no ordenada",
        ol: "Lista ordenada",
        htitle: "Títulos H1 - H6",
        paragraph: "Párrafo",
        header: "Encabezado",
        footer: "Pie de página",
        article: "Artículo",
        fieldset: "Grupo de campos",
        workspace: "Espacio de trabajo",
        trash: "🗑 Arrastra aquí para eliminar",
        param: "Parámetros",
        css: "Estilo",
        internflow: "Flujos internos",
        model: "Modelado",

        apply: "Aplicar",
        close: "Cerrar",
        idgen: "Id:",
        stypeclass: "Clase(s) de estilo:",
        titletitle: "Parámetros del título",
        sizetitle: "Tamaño del título:",
        alertsize: "El tamaño del título es obligatorio",

        lititle: "Parámetros del elemento de lista",
        lifor: "Este elemento es para:",
        liforul: "Lista no ordenada",
        liforol: "Lista ordenada",
        liforval: "Valor inicial:",
        alertval: "Por favor, introduce el valor inicial",

        atitle : "Parámetros del enlace",
        aurl: "URL de la página:",
        atarget: "Destino:",
        adefault: "Por defecto",
        ablank: "Nueva página en blanco",
        aparent: "Página padre",
        atop: "Página principal",
        amedia: "Tipo de medio:",
        amediaplaceholder: "Tipo MIME como 'text/html'",
        acontent: "Contenido:",
        adownload: "Enlace de descarga",
        alertacontent: "El contenido del enlace es obligatorio",

        buttontitle: "Parámetros del botón",
        buttoncontent: "Contenido:",
        alertbutton: "El contenido del botón es obligatorio",

        texttitle: "Parámetros del texto",
        textcontent: "Contenido:",

        spantitle: "Parámetros del área de texto",
        spancontent: "Contenido:",

        layouttitle: "Parámetros del diseño",
        layoutzonecount: "Número de zonas:",

        zonetitle: "Parámetros de la zona",

        pagetitle: "Parámetros de la página",
        pagename: "Nombre de la página:",
        pagepagettile: "Título de la página:",
        alertpagename: "El nombre de la página es obligatorio",

        imgtitle: "Parámetros de la imagen",
        imgstyle: "Estilo en línea:",
        imgsource: "Fuente:",

        blocktitle: "Parámetros de la división",
        blockstyle: "Estilo en línea:",

        labeltitle: "Parámetros de la etiqueta",
        labelfor: "Etiqueta para:",
        labelstyle: "Estilo en línea:",

        tftitle: "Parámetros del campo de texto",
        tfname: "Nombre:",
        tftype: "Tipo:",
        tftype1: "Texto",
        tftype2: "Contraseña",
        tftype3: "Archivo",
        tftype4: "Botón",
        tftype5: "Color",
        tftype6: "Fecha",
        tftype7: "Fecha local",
        tftype8: "Correo electrónico",
        tftype9: "Oculto",
        tftype10: "Casilla de verificación",
        tftype11: "Imagen",
        tftype12: "Mes",
        tftype13: "Número",
        tftype14: "Radio",
        tftype15: "Rango",
        tftype16: "Restablecer",
        tftype17: "Búsqueda",
        tftype18: "Enviar",
        tftype19: "Teléfono",
        tftype20: "Hora",
        tftype21: "URL",
        tfinitialval: "Valor inicial:",
        tfstyle: "Estilo en línea:",
        tfplaceholder: "Texto de marcador:",
        tfdisabled: "Deshabilitado",
        tfreadonly: "Solo lectura",
        tfrequired: "Obligatorio",
        tfmin: "Mínimo:",
        tfmax: "Máximo:",
        tfstep: "Paso:",
        tfcheck: "Marcado",
        tflongmax: "Longitud máxima:",

        formtitle: "Parámetros del formulario",
        formid: "Id:",
        formname: "Nombre:",
        formmethod: "Método:",
        formpost: "Datos ocultos (POST)",
        formget: "Datos en la URL (GET)",
        formtarget: "Destino:",
        formself: "Página actual",
        formblank: "Página en blanco",
        formparent: "Página padre",
        formtop: "Página principal",
        formenc: "Tipo de codificación:",
        formencdef: "Codificación por defecto",
        formencfile: "Codificación para archivos",
        formencplain: "Codificación para depuración",
        formnoval: "Desactivar validación"
    }
}

renderUI()