from packages.help.help import help

class date_help(help):
    def __init__(self, output):
        super().__init__(output)
        self.help_dict = {'now' : '',
                          'timestamp' : '',
                          'year' : '',
                          'year=' : '',
                          'month' : '',
                          'month=' : '',
                          'monthlname=' : '',
                          'monthsname=' : '',
                          'day' : '',
                          'day=' : '',
                          'daylname=' : '',
                          'daysname=' : '',
                          'hour' : '',
                          'hour=' : '',
                          'minut' : '',
                          'minut=' : '',
                          'second' : '',
                          'second=' : '',
                          'microsecond' : '',
                          'microsecond=' : '',
                          'fdate' : '',
                          'ftime' : '',
                          'fdt' : '',
                          'd+' : '',
                          'd-' : '',
                          '#monthdays' : '',
                          'd=' : '',
                          'd<>' : '',
                          'dt=' : '',
                          'dt<>' : '',
                          'dt<' : '',
                          'dt<=' : '',
                          'dt>' : '',
                          'dt>=' : '',
                          't=' : '',
                          't<>' : '',
                          '?leap' : '',
                          '#week' : ''}
