from packages.help.help import help

class db_help(help):
    def __init__(self, output):
        super().__init__(output)
        self.help_dict = {
            '?connect' : '''Returns the connection status with the database\nUsage : ( ... ) ?CONNECT ( true | false ... )''',
            'connect' : '''Connects Beetle to a database based on the identifiers contained in the variables 'hostname', 'dbname', 'username' and 'userpass'\nUsage : ( ... ) CONNECT ( ... )''',
            'disconnect' : '''Disconnect Beetle from the database to which it is connected\nUsage : ( ... ) DISCONNECT ( ... )''',
            '?close' : '''Returns the state of the connection cursor\nUsage : ( ... ) ?CLOSE ( true | false ... )''',
            'close' : '''Destroys the current cursor\nUsage : ( ... ) CLOSE ( ... )''',
            'hostname' : '''Variable storing the name of the host where the database is located. Default is 'localhost' ''',
            'dbname' : '''Variable storing the name of the database. Default is empty''',
            'username' : '''Variable storing the name of the user authorized to access the database. Default is 'root' ''',
            'userpass' : '''Variable storing the password of the user authorized to access the database. Default is empty''',
            'use' : '''Position the cursor on a particular database\nUsage : ( ... ) USE dbname ( ... )''',
            '|create>' : '''A marker that allows you to start a 'create' type query\nUsage : ( ... ) |CREATE> ( ... )''',
            '|show>' : '''A marker that allows you to start a 'show' type query\nUsage : ( ... ) |SHOW> ( ... )''',
            '|select>' : '''A marker that allows you to start a 'select' type query\nUsage : ( ... ) |SELECT> ( ... )''',
            '|insert>' : '''A marker that allows you to start a 'insert' type query\nUsage : ( ... ) |INSERT> ( ... )''',
            '|update>' : '''A marker that allows you to start a 'update' type query\nUsage : ( ... ) |UPDATE> ( ... )''',
            '|delete>' : '''A marker that allows you to start a 'delete' type query\nUsage : ( ... ) |DELETE> ( ... )''',
            '|drop>' : '''A marker that allows you to start a 'drop' type query\nUsage : ( ... ) |DROP> ( ... )''',
            '|truncate>' : '''A marker that allows you to start a 'truncate' type query\nUsage : ( ... ) |TRUNCATE> ( ... )''',
            '|alter>' : '''A marker that allows you to start a 'alter' type query\nUsage : ( ... ) |ALTER> ( ... )''',
            '>|' : '''A marker that allows you to terminate any type of query started with |create>, |show>, etc...\nUsage : ( ... ) >| ( ... )''',
            'chooseengine' : '''Allows you to select the type of database you want to use. Two values ​​are possible: mysql and postgresql. By default, mysql is selected.\nUsage : ( ... ) CHOOSEENGINE engine ( ... )''',
            'engine?' : '''Displays the selected database type\nUsage : ( ... ) ENGINE? ( mysql | postgresql ... )''',
            'dbcred' : '''Allows you to position the database identifiers\nUsage : ( "hostname" "username" "userpass" ... ) DBCRED ( ... )''',
            'createdb' : '''Creates and executes a 'create' query to create a database. The result is placed at the top of the data stack.\nUsage : ( dbname ... ) CREATEDB ( ... )''',
            'dropdb' : '''Creates and executes a 'drop' query to drop a database. The result is placed at the top of the data stack.\nUsage : ( "dbname" ... ) DROPDB ( ... )''',
            'createtab' : '''Creates and executes a 'create' query to create a table. The result is placed at the top of the data stack.\nUsage : ( "tabname" ... ) CREATETAB ( ... )''',
            'addcolumns' : '''Add one or more columns to a table\nUsage : ( "tabname" [ "`colname1` coldef1" "`colname2` coldef2" ... ] ... ) ADDCOLUMNS ( ... )''',
            'addforeignkey' : '''Add a foreign key to a table\nUsage : ( "desttabname" "origtabname" "cascade" ... ) ADDFOREIGNKEY ( ... )''',
            'addkey' : '''Add a key to a table. Type is one of this values : index | key | unique.\nUsage : \n\t( "tabname" "index" [ "nomindex" "columnsindex" ] ... ) ADDKEY ( ... )\n\t( "tabname" "key|unique" "columnname" ... ) ADDKEY ( ... )''',
            'changecol' : '''Modify a column in a table\nUsage : ( "tabname" "oldcolumnname" "newcolumnname" "newcolumndef" ... ) CHANGECOL ( ... )''',
            'desctab' : '''List the fields from a table\nUsage : ( "tabname" ... ) DESCTAB ( ... )''',
            'descdb' : '''List the tables in a database\nUsage : ( "dbname" ... ) DESCDB ( ... )''',
            'flist' : '''Extracts the list of field names from a table and presents the result in the form of a table.\nUsage : ( "tabname" desctab ... ) FLIST ( [ 'id', 'field1', ... ] ... )''',
            'fjoin' : '''From the values ​​in an array, this word constructs a string of characters\nUsage : ( "tabname" desctab flist ... ) FJOIN ( "(field1,field2,...)" ... )''',
            'add1record' : '''Adds a record to a table. Constructs and executes the 'insert' query for a single record. The id of the last record is placed on the data stack\nUsage : ( "tabname" [ record_fields_content ] ... ) ADD1RECORD ( lastid ... )''',
            'addrecords' : '''Adds multiple records to a table. Constructs and executes the 'insert' query. The id of the last record is placed on the data stack\nUsage : ( "tabname" [ [ record1_fields_content ] [ record2_fields_content ] ... ] ... ) ADDRECORDS ( lastid ... )''',
            'updaterecord' : '''Modifies one or more records based on a condition\nUsage : ( "tabname" "coltoupdate" "wherecond" ... ) UPDATERECORD ( ... )''',
            'deleterecord' : '''Deletes one or more records based on a condition\nUsage : ( "tabname" "wherecond" ... ) DELETERECORD ( ... )''',
            'selectrecord' : '''Returns records from a specific table based on a condition\nUsage : ( "tabname" "coltoselect" "wherecond" ... ) SELECTRECORD ( [ records ] ... )''',
            'droptable' : '''Deletes a table and the data it contains\nUsage : ( "tabname" ... ) DROPTABLE ( ... )''',
            'dropuser' : '''Deletes a user based on their id\nUsage : ( "username" ... ) DROPUSER ( ... )''',
            'trunctable' : '''Deletes all data contained in a table\nUsage : ( "tabname" ... ) TRUNCTABLE ( ... )'''
        }
