from packages.help.help import help

class math_help(help):
    def __init__(self, output):
        super().__init__(output)
        self.help_dict = {
            'fib' : '''Display the count first numbers of Fibonacci sequence\nUsage : ( n ... ) FIB ( ... )''',
            '#fib' : '''Display the nth number of the Fibonacci sequence\nUsage : ( n ... ) #FIB ( ... )''',
            'cos' : '''Give the cosinus of a number in radians\nUsage : ( n ... ) COS ( cos(n) ... )''',
            'sin' : '''Give the sinus of a number in radians\nUsage : ( n ... ) SIN ( sin(n) ... )''',
            'tan' : '''Give the tangente of a number in radians\nUsage : ( n ... ) TAN ( tan(n) ... )''',
            'comb' : '''Give the number of ways to choose k items from n items without repetition and without order\nUsage : ( n k ... ) COMB ( comb(n, k) ... )''',
            'perm' : '''Give the number of ways to choose k items from n items without repetition and with order\nUsage : ( n k ... ) PERM ( perm(n, k) ... )''',
            'fact' : '''Give the factorial of n\nUsage : ( n ... ) FACT ( fact(n) ... )''',
            'random' : '''Give a random number between 0 and 1\nUsage : ( ... ) RANDOM ( random_number ... )''',
            'intrand' : '''Give a random integer between bottom number and top number\nUsage : ( bottom_number top_number ... ) INTRAND ( random_integer ... )''',
            'floatrand' : '''Give a random float between bottom number and top number\nUsage : ( bottom_number top_number ... ) FLOATRAND ( random_float ... )''',
            'square' : '''Give the square of a number\nUsage : ( n ... ) SQUARE ( n*n ... )''',
            'cube' : '''Give the cube of a number\nUsage : ( n ... ) CUBE ( n*n*n ... )''',
            'pow' : '''''', 
            'abs' : '''''',
            'sqrt' : '''''',
            'log10' : '''''',
            'log2' : '''''',
            'log1p' : '''''',
            'log' : '''''',
            'exp' : '''''',
            'exp2' : '''''',
            'expm1' : '''''',
            'cbrt' : '''''',
            'ceil' : '''''',
            'floor' : '''''',
            'remainder' : '''''',
            'mod' : '''''',
            'round' : '''''',
            'f.' : '''''',
            'trunc' : '''''',
            '>deg' : '''''',
            '>rad' : '''''',
            'acos' : '''''',
            'asin' : '''''',
            'atan' : '''''',
            'atan2' : '''''',
            'acosh' : '''''',
            'asinh' : '''''',
            'atanh' : '''''',
            'cosh' : '''''',
            'sinh' : '''''',
            'tanh' : '''''',
            'hypot' : '''''',
            'sum' : '''''',
            'prod' : '''''',
            'closed' : '''''',
            '.m' : '''''',
            'dim' : '''''',
            'mminor' : '''''',
            'mcofactor' : '''''',
            'mdet' : '''''',
            'id2' : '''''',
            'id3' : '''''',
            'id4' : '''''',
            'norm' : '''''',
            'm+' : '''''',
            'm-' : '''''',
            'm*' : '''''',
            'mscalar*' : '''''',
            'mscalar+' : '''''',
            'mscalar-' : '''''',
            'msub' : '''''',
            'mtrans' : '''''',
            'mcofactor-matrix' : '''''',
            'madjucate' : '''''',
            'minv' : '''''',
            'complex' : '''''',
            're' : '''''',
            'im' : '''''',
            'c+' : '''''',
            'c-' : '''''',
            'c*' : '''''',
            'cscalar*' : '''''',
            'cscalar+' : '''''',
            'cscalar-' : '''''',
            'cconj' : '''''',
            'mconj' : '''''',
            'madjoint' : '''''',
            'pi' : '''''', 
            'pi>deg' : '''''', 
            'pi/2' : '''''', 
            'pi/2>deg' : '''''', 
            'pi/3' : '''''', 
            'pi/3>deg' : '''''', 
            'pi/4' : '''''', 
            'pi/4>deg' : '''''', 
            '3pi/2' : '''''', 
            '3pi/2>deg' : '''''', 
            '3pi/4' : '''''', 
            '3pi/4>deg' : '''''', 
            't' : '''''', 
            'c' : '''''', 
            'e' : '''''',
            'h' : '''''', 
            'g' : ''''''
        }
