from packages.help.help import help

class math_help(help):
    def __init__(self, output):
        super().__init__(output)
        self.help_dict = {
            'fib' : '''Display the count first numbers of Fibonacci sequence\nUsage : ( n ... ) FIB ( ... )''',
            '#fib' : '''Display the nth number of the Fibonacci sequence\nUsage : ( n ... ) #FIB ( ... )''',
            'cos' : '''Give the cosinus of a number in radians\nUsage : ( n ... ) COS ( cos(n) ... )''',
            'sin' : '''Give the sinus of a number in radians\nUsage : ( n ... ) SIN ( sin(n) ... )''',
            'tan' : '''Give the tangente of a number in radians\nUsage : ( n ... ) TAN ( tan(n) ... )''',
            'comb' : '''Give the number of ways to choose k items from n items without repetition and without order\nUsage : ( n k ... ) COMB ( comb(n, k) ... )''',
            'perm' : '''Give the number of ways to choose k items from n items without repetition and with order\nUsage : ( n k ... ) PERM ( perm(n, k) ... )''',
            'fact' : '''Give the factorial of n\nUsage : ( n ... ) FACT ( fact(n) ... )''',
            'random' : '''Give a random number between 0 and 1\nUsage : ( ... ) RANDOM ( random_number ... )''',
            'intrand' : '''Give a random integer between bottom number and top number\nUsage : ( bottom_number top_number ... ) INTRAND ( random_integer ... )''',
            'floatrand' : '''Give a random float between bottom number and top number\nUsage : ( bottom_number top_number ... ) FLOATRAND ( random_float ... )''',
            'square' : '''Give the square of a number\nUsage : ( n ... ) SQUARE ( n*n ... )''',
            'cube' : '''Give the cube of a number\nUsage : ( n ... ) CUBE ( n*n*n ... )''',
            'pow' : '''Give the nth power of a number\nUsage : ( n p ... ) POW ( n^p ... )''', 
            'abs' : '''Give the absolute value of a number\nUsage : ( -n ... ) ABS ( n ... )''',
            'sqrt' : '''Give the square root of a number\nUsage : ( n ... ) SQRT ( sqrt(n) ... )''',
            'log10' : '''Returns the base-10 logarithm of a number\nUsage : ( n ... ) LOG10 ( log10(n) ... )''',
            'log2' : '''Returns the base-2 logarithm of a number\nUsage : ( n ... ) LOG2 ( log2(n) ... )''',
            'log1p' : '''Returns the natural logarithm of 1+n\nUsage : ( n ... ) LOG1P ( log(1+n) ... )''',
            'log' : '''Returns the natural logarithm of a number, or the logarithm of number to base\nUsage : ( n ... ) LOG ( log(n) ... )''',
            'exp' : '''Returns e raised to the power of n\nUsage : ( n ... ) EXP ( e^n ... )''',
            'exp2' : '''Returns 2 raised to the power n\nUsage : ( n ... ) EXP2 ( 2^n ... )''',
            'expm1' : '''Returns e^n - 1\nUsage : ( n ... ) EXPM1 ( e^n - 1 ... )''',
            'cbrt' : '''Returns the cube root of a number\nUsage : ( n ... ) CBRT ( cbrt(n) ... )''',
            'ceil' : '''Returns the ceiling of n, the smallest integer greater than or equal to n\nUsage : ( n ... ) CEIL ( ceil(n) ... )''',
            'floor' : '''Returns the floor of n, the largest integer less than or equal to n\nUsage : ( n ... ) FLOOR ( floor(n) ... )''',
            'remainder' : '''Returns the remainder of n with respect to m\nUsage : ( n m ... ) REMAINDER ( remainder(n, m) ... )''',
            'mod' : '''Returns the modulo of n in m\nUsage : ( n m ... ) MOD ( count_of_n_in_m ... )''',
            'round' : '''Returns the rounded value of a number to a given precision\nUsage : ( n p ... ) ROUND ( m ... )''',
            'f.' : '''Returns the rounded value of a number with a precision of 12 decimal places\nUsage : ( n ... ) F. ( m ... )''',
            'trunc' : '''Returns the integer part of n\nUsage : ( n ... ) TRUNC ( integer_part(n) ... )''',
            '>deg' : '''Convert angle n from radians to degrees\nUsage : ( n ... ) >DEG ( n_in_degrees ... )''',
            '>rad' : '''Convert angle n from degrees to radians\nUsage : ( n ... ) >RAD ( n_in_radians ... )''',
            'acos' : '''Returns the arc cosine of n\nUsage : ( n ... ) ACOS ( m ... )''',
            'asin' : '''Returns the arc sine of n\nUsage : ( n ... ) ASIN ( m ... )''',
            'atan' : '''Returns the arc tangent of n\nUsage : ( n ... ) ATAN ( m ... )''',
            'atan2' : '''Returns the atan(y / x)\nUsage : ( x y ... ) ATAN2 ( m ... )''',
            'acosh' : '''Retuns the inverse hyperbolic cosine of n\nUsage : ( n ... ) ACOSH ( m ... )''',
            'asinh' : '''Returns the inverse hyperbolic sine of n\nUsage : ( n ... ) ASINH ( m ... )''',
            'atanh' : '''Returns the inverse hyperbolic tangent of n\nUsage : ( n ... ) ATANH ( m ... )''',
            'cosh' : '''Returns the hyperbolic cosine of n\nUsage : ( n ... ) COSH ( m ... )''',
            'sinh' : '''Returns the hyperbolic sine of n\nUsage : ( n ... ) SINH ( m ... )''',
            'tanh' : '''Returns the hyperbolic tangent of n\nUsage : ( n ... ) TANH ( m ... )''',
            'hypot' : '''Returns the radius of the circle that is represented by the hypotenuse of a right triangle\nUsage : ( n m ... ) HYPOT ( x ... )''',
            'sum' : '''Returns the sum of values in an array\nUsage : ( [ n1 n2 n3 ... ] ... ) SUM ( n1+n2+n3+... ... )''',
            'prod' : '''Returns the product of elements in an array\nUsage : ( [ n1 n2 n3 ... ] ... ) PROD ( n1*n2*n3*... ... )''',
            'closed' : '''Check if the values a and b are close to each other\nUsage : ( a b ... ) CLOSED ( true | false ... )''',
            '.m' : '''Formats the aij values ​​of a matrix to remove the error introduced by Python and displays the corrected matrix\nUsage : ( m ... ) .m ( correct_m ... )''',
            'dim' : '''Returns the cardinality of a matrix\nUsage : ( m ... ) DIM ( [row_dim, col_dim] ... )''',
            'mminor' : '''Returns a minor of a matrix without r row and c column\nUsage : ( r c m ... ) MMINOR ( m' ... )''',
            'mcofactor' : '''Returns the cofactor of a matrix at coordinates i and j\nUsage : ( i j m ... ) MCOFACTOR ( value ... )''',
            'mdet' : '''Returns the determinant of a matrix\nUsage : ( m ... ) MDET ( det ... )''',
            'id2' : '''Returns the non-complex 2x2 identity matrix''',
            'id3' : '''Returns the non-complex 3x3 identity matrix''',
            'id4' : '''Returns the non-complex 4x4 identity matrix''',
            'norm' : '''''',
            'm+' : '''''',
            'm-' : '''''',
            'm*' : '''''',
            'mscalar*' : '''''',
            'mscalar+' : '''''',
            'mscalar-' : '''''',
            'msub' : '''''',
            'mtrans' : '''''',
            'mcofactor-matrix' : '''''',
            'madjucate' : '''''',
            'minv' : '''''',
            'complex' : '''''',
            're' : '''''',
            'im' : '''''',
            'c+' : '''''',
            'c-' : '''''',
            'c*' : '''''',
            'cscalar*' : '''''',
            'cscalar+' : '''''',
            'cscalar-' : '''''',
            'cconj' : '''''',
            'mconj' : '''''',
            'madjoint' : '''''',
            'pi' : '''Returns the constant Pi in radians''', 
            'pi>deg' : '''Returns the constant Pi in degrees''', 
            'pi/2' : '''Returns the constant Pi/2 in radians''', 
            'pi/2>deg' : '''Returns the constant Pi/2 in degrees''', 
            'pi/3' : '''Returns the constant Pi/3 in radians''', 
            'pi/3>deg' : '''Returns the constant Pi/3 in degrees''', 
            'pi/4' : '''Returns the constant Pi/4 in radians''', 
            'pi/4>deg' : '''Returns the constant Pi/4 in degrees''', 
            '3pi/2' : '''Returns the constant 3Pi/2 in radians''', 
            '3pi/2>deg' : '''Returns the constant 3Pi/2 in degrees''', 
            '3pi/4' : '''Returns the constant 3Pi/4 in radians''', 
            '3pi/4>deg' : '''Returns the constant 3Pi/4 in degrees''', 
            't' : '''Returns the constant Tau''', 
            'c' : '''Returns the speed of light''', 
            'e' : '''Returns Euler's constant''',
            'h' : '''Returns Planck's constant: the quantum of energy''', 
            'g' : '''Returns the gravitational constant'''
        }
