from packages.help.help import help

class math_help(help):
    def __init__(self, output):
        super().__init__(output)
        self.help_dict = {'fib' : 'Display the count first numbers of Fibonacci sequence\nUsage : ( n ... ) FIB ( ... )',
                          '#fib' : 'Display the nth number of the Fibonacci sequence\nUsage : ( n ... ) #FIB ( ... )',
                          'cos' : 'Give the cosinus of a number in radians\nUsage : ( n ... ) COS ( cos(n) ... )',
                          'sin' : 'Give the sinus of a number in radians\nUsage : ( n ... ) SIN ( sin(n) ... )',
                          'tan' : 'Give the tangente of a number in radians\nUsage : ( n ... ) TAN ( tan(n) ... )',
                          'comb' : 'Give the number of ways to choose k items from n items without repetition and without order\nUsage : ( n k ... ) COMB ( comb(n, k) ... )',
                          'perm' : 'Give the number of ways to choose k items from n items without repetition and with order\nUsage : ( n k ... ) PERM ( perm(n, k) ... )',
                          'fact' : 'n factorial\nUsage : ( n ... ) FACT ( fact(n) ... )',
                          'square' : '',
                          'cube' : '',
                          'pow' : '', 
                          'abs' : '',
                          'sqrt' : '',
                          'log10' : '',
                          'log2' : '',
                          'log1p' : '',
                          'log' : '',
                          'exp' : '',
                          'exp2' : '',
                          'expm1' : '',
                          'cbrt' : '',
                          'ceil' : '',
                          'floor' : '',
                          'remainder' : '',
                          'mod' : '',
                          'round' : '',
                          'trunc' : '',
                          '>deg' : '',
                          '>rad' : '',
                          'acos' : '',
                          'asin' : '',
                          'atan' : '',
                          'atan2' : '',
                          'acosh' : '',
                          'asinh' : '',
                          'atanh' : '',
                          'cosh' : '',
                          'sinh' : '',
                          'tanh' : '',
                          'point' : '',
                          'vector' : '',
                          'matrix' : '',
                          'x' : '',
                          'det' : '',
                          'id2d' : '',
                          'id3d' : '',
                          'id4d' : '',
                          'norm' : '',
                          'pi' : '', 
                          'pi>deg' : '', 
                          'pi/2' : '', 
                          'pi/2>deg' : '', 
                          'pi/3' : '', 
                          'pi/3>deg' : '', 
                          'pi/4' : '', 
                          'pi/4>deg' : '', 
                          '3pi/2' : '', 
                          '3pi/2>deg' : '', 
                          '3pi/4' : '', 
                          '3pi/4>deg' : '', 
                          'tau' : '', 
                          'c' : '', 
                          'e' : '',
                          'h' : '', 
                          'g' : ''}
