from packages.help.help import help

class mq_help(help):
    def __init__(self, output):
        super().__init__(output)
        self.help_dict = {
            'σx' : '''Pauli sigma matrix as a function of x. This word places the matrix on the working stack. It is a matrix of complexes.''',
            'σy' : '''Pauli sigma matrix as a function of y. This word places the matrix on the working stack. It is a matrix of complexes.''',
            'σz' : '''Pauli sigma matrix as a function of z. This word places the matrix on the working stack. It is a matrix of complexes.''',
            'phi' : '''Give it the character phi and place it on the working stack''',
            'psi' : '''Give it the character psi and place it on the working stack''',
            'sigma' : '''Give it the character sigma and place it on the working stack''',
            'alpha' : '''Give it the character alpha and place it on the working stack''',
            'beta' : '''Give it the character beta and place it on the working stack''',
            'delta' : '''Give it the character delta and place it on the working stack''',
            'epsilon' : '''Give it the character epsilon and place it on the working stack''',
            'lambda' : '''Give it the character lambda and place it on the working stack''',
            'mu' : '''Give it the character mu and place it on the working stack''',
            'omega' : '''Give it the character omega and place it on the working stack''',
            'nu' : '''Give it the character nu and place it on the working stack''',
            'tau' : '''Give it the character tau and place it on the working stack''',
            'omicron' : '''Give it the character omicron and place it on the working stack''',
            'theta' : '''Give it the character theta and place it on the working stack''',
            'ket' : '''This word constructs a ket, creating a constant whose name is of the form |state>. A ket is a column vector.\nUsage : ( content "state" ... ) KET ( k ... )\nExemple : |ψ> = [ [ a ] [ b ] [ c ] ] where a, b, c are complex numbers ; a = [ re(a) im(a) ], same for b et c''',
            'bra' : '''This word constructs a bra, creating a constant whose name is of the form <state|. A bra is a line vector.\nUsage : ( content "state" ... ) BRA ( k ... )\nExemple : <ψ| = [ a* b* c* ] where a, b, c are complex numbers ; a = [ re(a) im(a) ], same for b et c''',
            'braket' : '''This word constructs a braket, creating a constant whose name is of the form <brastate|ketstate>. A braket is a number.''',
            '>bra' : '''This word places the corresponding bra of a ket on the work pile\nUsage : ( k ... ) >BRA ( b ... )''',
            '>ket' : '''This word places the corresponding ket of a bra on the work pile\nUsage : ( b ... ) >KET ( k ... )''',
            'braket*' : '''Dot product of bra and ket and provides a scalar\nUsage : ( b k ... ) BRAKET* ( n ... )''',
            'ktensor' : '''This word allows you to perform a tensor product between two entities or Kronecker product : a b -- a ⊗ b\nUsage : ( a b ... ) KTENSOR ( a ⊗ b ... )\nExemple : \n\tFor ket, -- |0> |1> ktensor -- gives |0> ⊗ |1> = |01> represented as a 4x1 vector\n\tFor opérators, -- hgate hgate ktensor -- gives H ⊗ H a 4×4 matrix, applicable to a 2-qubit state''',
            '|0>' : '''Give the ket corresponding to quantum state 0 in the form of a matrix\nUsage : ( ... ) |0> ( [ complex matrix ] ... )''',
            '|1>' : '''Give the ket corresponding to quantum state 1 in the form of a matrix\nUsage : ( ... ) |1> ( [ complex matrix ] ... )''',
            '<0|' : '''Give the bra corresponding to quantum state 0 in the form of a matrix\nUsage : ( ... ) <0| ( [ complex matrix ] ... )''',
            '<1|' : '''Give the bra corresponding to quantum state 1 in the form of a matrix\nUsage : ( ... ) <1| ( [ complex matrix ] ... )''',
            '|+>' : '''Give the ket corresponding to quantum state + in the form of a matrix. |+> is equal to 1/sqrt(2) * (|0> + |1>)\nUsage : ( ... ) |+> ( [ complex matrix ] ... )''',
            '|->' : '''Give the ket corresponding to quantum state - in the form of a matrix. |-> is equal to 1/sqrt(2) * (|0> - |1>)\nUsage : ( ... ) |-> ( [ complex matrix ] ... )''',
            '<+|' : '''Give the bra corresponding to quantum state + in the form of a matrix\nUsage : ( ... ) <+| ( [ complex matrix ] ... )''',
            '<-|' : '''Give the bra corresponding to quantum state - in the form of a matrix\nUsage : ( ... ) <-| ( [ complex matrix ] ... )''',
            'hgate' : '''This word represents the Hadamard quantum gate, which corresponds to 1 / sqrt(2) * [ [ 1 1 ] [ 1 -1 ] ]. The matrix values ​​are complex numbers\nUsage : ( ... ) hgate ( [ complex matrix ] ... )''',
            'hmeasure' : '''This word allows us to calculate the probability of measuring |0> and |1> on the state H x |0>\nUsage : ( ... ) hmeasure ( ... )''',
            'igate' : '''This word represents the Identity quantum gate, which corresponds to [ [ 1 0 ] [ 0 1 ] ]. The matrix values ​​are complex numbers\nUsage : ( ... ) igate ( [ complex matrix ] ... )''',
            'sgate' : '''This word represents the Phase quantum gate, which corresponds to [ [ 1 0 ] [ 0 i ] ]. The matrix values ​​are complex numbers\nUsage : ( ... ) sgate ( [ complex matrix ] ... )''',
            'tgate' : '''This word represents the T (pi/8) quantum gate, which corresponds to [ [ 1 0 ] [ cos(pi/4) i*sin(pi/4) ] ]. The matrix values ​​are complex numbers\nUsage : ( ... ) tgate ( [ complex matrix ] ... )''',
            'cnot' : '''This word represents the cnot quantum gate, which corresponds to [ [ 1 0 0 0 ] [ 0 1 0 0 ] [ 0 0 0 1 ] [ 0 0 1 0 ] ]. The matrix values ​​are complex numbers\nUsage : ( ... ) cnot ( [ complex matrix ] ... )''',
            'nqubits' : '''This word returns the matrix corresponding to the ket you compose from a string. You can generate a state with a 6-qubit composition this way.\nThe string you provide to the word must contain only 0s or 1s.\nUsage : ( str ... ) nqubits ( [ complex matrix ] ... )\nExemple : "010101" nqubits -> |010101>''',
            'allnqubits' : '''This word generates all n-qubit kets into constants\nUsage : ( n ... ) ALLNQUBITS ( ... )''',
            'p0' : '''This word calculates the projector relative to |0>, this corresponds to |0><0|''',
            'p1' : '''This word calculates the projector relative to |1>, this corresponds to |1><1|''',
            'proj&prob' : '''This word calculates the probability of obtaining a ket through a projector. It requires a projector and a ket.''',
            'normalize-measure' : '''This word calculates the norm of a measurement''',
            'measure' : '''This word performs a measurement''',
            'random-measure' : '''This word performs a random measurement between measurements with projector P0 and projector P1''',
            'partial-proj' : '''This word performs a partial projector from an n-qubit at position k; k > 0''',
            'random-measure-qubit' : '''This word performs a random measurement between measurements with a partial projector'''
        }
