from packages.help.help import help

class mq_help(help):
    def __init__(self, output):
        super().__init__(output)
        self.help_dict = {
            'σx' : '''Pauli sigma matrix as a function of x. This word places the matrix on the working stack. It is a matrix of complexes.''',
            'σy' : '''Pauli sigma matrix as a function of y. This word places the matrix on the working stack. It is a matrix of complexes.''',
            'σz' : '''Pauli sigma matrix as a function of z. This word places the matrix on the working stack. It is a matrix of complexes.''',
            'phi' : '''Give it the character phi and place it on the working stack''',
            'psi' : '''Give it the character psi and place it on the working stack''',
            'sigma' : '''Give it the character sigma and place it on the working stack''',
            'alpha' : '''Give it the character alpha and place it on the working stack''',
            'beta' : '''Give it the character beta and place it on the working stack''',
            'delta' : '''Give it the character delta and place it on the working stack''',
            'epsilon' : '''Give it the character epsilon and place it on the working stack''',
            'lambda' : '''Give it the character lambda and place it on the working stack''',
            'mu' : '''Give it the character mu and place it on the working stack''',
            'omega' : '''Give it the character omega and place it on the working stack''',
            'nu' : '''Give it the character nu and place it on the working stack''',
            'tau' : '''Give it the character tau and place it on the working stack''',
            'omicron' : '''Give it the character omicron and place it on the working stack''',
            'theta' : '''Give it the character theta and place it on the working stack''',
            'ket' : '''This word constructs a ket, creating a constant whose name is of the form |state>. A ket is a column vector.\nUsage : ( content "state" ... ) KET ( k ... )\nExemple : |ψ> = [ [ a ] [ b ] [ c ] ] where a, b, c are complex numbers ; a = [ re(a) im(a) ], same for b et c''',
            'bra' : '''This word constructs a bra, creating a constant whose name is of the form <state|. A bra is a line vector.\nUsage : ( content "state" ... ) BRA ( k ... )\nExemple : <ψ| = [ a* b* c* ] where a, b, c are complex numbers ; a = [ re(a) im(a) ], same for b et c''',
            'braket' : '''This word constructs a braket, creating a constant whose name is of the form <brastate|ketstate>. A braket is a number.''',
            '>bra' : '''This word places the corresponding bra of a ket on the work pile\nUsage : ( k ... ) >BRA ( b ... )''',
            '>ket' : '''This word places the corresponding ket of a bra on the work pile\nUsage : ( b ... ) >KET ( k ... )''',
            'braket*' : '''Dot product of bra and ket and provides a scalar\nUsage : ( b k ... ) BRAKET* ( n ... )''',
            'ktensor' : '''This word allows you to perform a tensor product between two entities or Kronecker product : a b -- a ⊗ b\nUsage : ( a b ... ) KTENSOR ( a ⊗ b ... )\nExemple : \n\tFor ket, |0> |1> ktensor gives |0> ⊗ |1> = |01> represented as a 4x1 vector\n\tFor opérators, hgate hgate ktensor gives H ⊗ H a 4×4 matrix, applicable to a 2-qubit state''',
            '|0>' : '''''',
            '|1>' : '''''',
            '<0|' : '''''',
            '<1|' : '''''',
            '|+>' : '''''',
            '|->' : '''''',
            '<+|' : '''''',
            '<-|' : '''''',
            'hgate' : '''''',
            'hmeasure' : '''''',
            'igate' : '''''',
            'sgate' : '''''',
            'tgate' : '''''',
            'cnot' : '''''',
            'nqubits' : '''''',
            'allnqubits' : '''''',
            'p0' : '''''',
            'p1' : '''''',
            'proj&prob' : '''''',
            'normalize-measure' : '''''',
            'measure' : '''''',
            'random-measure' : '''''',
            'partial-proj' : '''''',
            'random-measure-qubit' : ''''''
        }
