from packages.help.help import help

class web_help(help):
    def __init__(self, output):
        super().__init__(output)
        self.help_dict = {
            'generate' : '''Generate all yours pages\nUsage : ( container_content ... ) GENERATE ( html_content ... )''',
            'webreset' : '''Create all the variables that make up your page. The created variables have the following names : html, head, body. The different components of your page are linked. body and head are in html. \nUsage : ( ... ) WEBRESET ( ... )''',
            'addcontent' : '''This word allows you to add content in a container type tag.\nUsage : ( content tag content ... ) ADDCONTENT ( ... )''',
            'addattr' : '''This word allows you to add an attribute in a tag.\nUsage : ( "tag" "attribut_name" "attribut_value" ... ) ADDATTR ( ... )''',
            'fieldarea' : '''Create an input (html). Attribut name of fieldarea is equal to attribut id. It is not a container.\nUsage ( "type_attribut" "value_attribut" "id_attribut" ... ) FIELDAREA ( ... )''',
            'div' : '''Create a division (div in html). It is a container.\nUsage : ( "id_attribut" ... ) DIV ( ... )''',
            'label' : '''Create a label (label in html). It is a container.\nUsage : ( "content" "for_attribut" ... ) LABEL ( ... )''',
            'headlink' : '''Create a link in head. (link in html). It is not a container.\nUsage : ( "href_attribut" ... ) HEADLINK ( ... )''',
            'headscriptfile' : '''Create a script referencing a javascript file in the head. It is not a container.\nUsage : ( mode src ... ) HEADSCRIPTFILE ( ... )''',
            'script': '''Create a script not referenced in a javascript file in the head. It is a container.\nUsage : ( mode content ... ) SCRIPT ( ... )''',
            'img' : '''Create an image (img in html). It is not a container. You have to control the size of your image with addattr word or by css properties.\nUsage : ( "src_attribut" ... ) IMG ( ... )''',
            'textarea' : '''Create a multiline fieldarea (textarea in html). It is a container. You have to control the size of your textarea with addattr word or by css properties.\nUsage : ( "id_attribut" ... ) TEXTAREA ( ... )''',
            'br' : '''Create a carriage return.\nUsage : ( ... ) BR ( ... )''',
            'select' : '''''',
            'option' : '''''',
            'a' : '''''',
            'button' : '''''',
            'header' : '''''',
            'footer' : '''''',
            'article' : '''''',
            'style' : '''''',
            'paragraph' : '''''',
            'maintitle' : '''''',
            'span' : '''''',
            'strong' : '''''',
            'small' : '''''',
            'underline' : '''''',
            'table' : '''''',
            'th' : '''''',
            'td' : '''''',
            'row' : '''''',
            'tablerow' : '''''',
            'tablecell' : '''''',
            'tablehead' : '''''',
            'unorderlist' : '''''',
            'orderlist' : '''''',
            'listitem' : '''''',
            'urlbase' : '''''',
            'charset' : '''''',
            'httpequiv' : '''''',
            'meta' : '''''',
            'comment' : '''''',
            'abbr': '''''',
            'address': '''''',
            'area': '''''',
            'map': '''''',
            'aside': '''''',
            'audio': '''''',
            'source': '''''',
            'pictsrc': '''''',
            'bold': '''''',
            'bdo': '''''',
            'blockquote': '''''',
            'canvas': '''''',
            'caption': '''''',
            'cite': '''''',
            'code': '''''',
            'col': '''''',
            'colgroup': '''''',
            'data': '''''',
            'datalist': '''''',
            'dloption': '''''',
            'dl': '''''',
            'dt': '''''',
            'dd': '''''',
            'del': '''''',
            'details': '''''',
            'dfn': '''''',
            'dialog': '''''',
            'em': '''''',
            'fieldset': '''''',
            'figcaption': '''''',
            'figure': '''''',
            'form': '''''',
            'hr': '''''',
            'italic': '''''',
            'iframe': '''''',
            'ins': '''''',
            'kbd': '''''',
            'legend': '''''',
            'main': '''''',
            'mark': '''''',
            'menu': '''''',
            'meter': '''''',
            'nav': '''''',
            'noscript': '''''',
            'optgroup': '''''',
            'picture': '''''',
            'pre': '''''',
            'quote': '''''',
            'section': '''''',
            'sub': '''''',
            'summary': '''''',
            'sup': '''''',
            'svg': '''''',
            'svgrect': '''''',
            'svgpolygon': '''''',
            'svgellipse': '''''',
            'svgcircle': '''''',
            'svgline': '''''',
            'svgpolyline': '''''',
            'svgpath': '''''',
            'svgtext': '''''',
            'svgtextpath': '''''',
            'svgimage': '''''',
            'svgmarker': '''''',
            'svglineargradient': '''''',
            'svgradialgradient': '''''',
            'svgpattern': '''''',
            'video': '''''',
            'layoutgrid' : '''''',
            'layoutarea' : '''''',
            'layout' : '''''',
            'savelaystyle' : '''''',
            'grouplaystyle' : '''''',
            'posted' : '''''',
            'redirect' : '''''',
            'htmlcontent' : '''''',
            'session' : '''''',
            'getsession' : '''''',
            'setsessvar' : '''''',
            'getsessvar' : '''''',
            'session?' : '''''',
            'setsessduration' : '''''',
            'sessduration?' : '''''',
            'completeselect' : '''''',
            'card' : '''''',
            'addcardtitle' : '''''',
            'addcardbody' : '''''',
            'addcardbottom' : '''''',
            'flipcard' : '''''',
            'profilecard' : '''''',
            'productcard' : '''''',
            'splitter' : '''''',
            'divider' : '''''',
            'overlay' : '''''',
            'tab' : '''''',
            'accordion' : '''''',
            'sidenav' : '''''',
            'topnav' : '''''',
            'filteredlist' : '''''',
            'modal' : ''''''
        }