from packages.help.help import help

class web_help(help):
    def __init__(self, output):
        super().__init__(output)
        self.help_dict = {
            'generate' : '''Generate all yours pages\nUsage : ( container_content ... ) GENERATE ( html_content ... )''',
            'webreset' : '''Create all the variables that make up your page. The created variables have the following names : html, head, body. The different components of your page are linked. body and head are in html. \nUsage : ( ... ) WEBRESET ( ... )''',
            'addcontent' : '''This word allows you to add content in a container type tag.\nUsage : ( content tag content ... ) ADDCONTENT ( ... )''',
            'addattr' : '''This word allows you to add an attribute in a tag.\nUsage : ( "tag" "attribut_name" "attribut_value" ... ) ADDATTR ( ... )''',
            'fieldarea' : '''Create an input (html). Attribut name of fieldarea is equal to attribut id. It is not a container.\nUsage ( "type_attribut" "value_attribut" "id_attribut" ... ) FIELDAREA ( ... )''',
            'div' : '''Create a division (div in html). It is a container.\nUsage : ( "id_attribut" ... ) DIV ( ... )''',
            'label' : '''Create a label (label in html). It is a container.\nUsage : ( "content" "for_attribut" ... ) LABEL ( ... )''',
            'headlink' : '''Create a link in head. (link in html). It is not a container.\nUsage : ( "href_attribut" ... ) HEADLINK ( ... )''',
            'headscriptfile' : '''Create a script referencing a javascript file in the head. It is not a container.\nUsage : ( mode src ... ) HEADSCRIPTFILE ( ... )''',
            'script': '''Create a script not referenced in a javascript file in the head. It is a container.\nUsage : ( mode content ... ) SCRIPT ( ... )''',
            'img' : '''Create an image (<img> in html). It is not a container. You have to control the size of your image with addattr word or by css properties.\nUsage : ( "src_attribut" ... ) IMG ( ... )''',
            'textarea' : '''Create a multiline fieldarea (<textarea> in html). It is a container. You have to control the size of your textarea with addattr word or by css properties.\nUsage : ( "id_attribut" ... ) TEXTAREA ( ... )''',
            'br' : '''Create a carriage return (<br> in html). It is not a container.\nUsage : ( ... ) BR ( ... )''',
            'select' : '''Create a select tag without option (<select> in html). It is a container.\nUsage ( id_attribut ... ) SELECT ( ... )''',
            'option' : '''Create a select option tag (<option> in html). It is a container. You can decide if your option is selected or not. A content and value is mandatory.\nUsage : ( "content" "value_attribut" "selected_attribut" ... ) OPTION ( ... )''',
            'a' : '''Create an anchor tag (<a> in html). It is a container.\nUsage : ( "content" "href_attribut" ... ) A ( ... )''',
            'button' : '''Create a simple button tag (<button> in html). It is a container.\nUsage : ( "content" "type_attribut" ... ) BUTTON ( ... )''',
            'header' : '''Create an header tag (<header> in html). It is a container.\nUsage : ( ... ) HEADER ( ... )''',
            'footer' : '''Create a footer tag (<footer> in html). It is a container.\nUsage : ( ... ) FOOTER ( ... )''',
            'article' : '''Create an article tag (<article> in html). It is a container.\nUsage : ( ... ) ARTICLE ( ... )''',
            'style' : '''Create a style tag (<style> in html). It is a container.\nUsage : ( "content" ... ) STYLE ( ... )''',
            'paragraph' : '''Create a paragraph tag (<p> in html). It is a container.\nUsage : ( "content" ... ) PARAGRAPH ( ... )''',
            'maintitle' : '''Create a title tag (<h1>, <h2>, <h3>, <h4>, <h5>, <h6> in html). It is a container.\nUsage : ( size_attribut, "content" ... ) MAINTITLE ( ... )''',
            'span' : '''Create a simple division tag (<span> in html). It is a container.\nUsage : ( "content" ... ) SPAN ( ... )''',
            'strong' : '''Create a strong text tag (<strong> in html). It is a container.\nUsage : ( "content" ... ) STRONG ( ... )''',
            'small' : '''Create a small text tag (<small> in html). It is a container.\nUsage : ( "content" ... ) SMALL ( ... )''',
            'underline' : '''Create an underlined text tag (<u> in html). It is a container.\nUsage : ( "content" ... ) UNDERLINE ( ... )''',
            'table' : '''Create a table tag (<table> in html). It is a container.\nUsage : ( "id_attribut" ... ) TABLE ( ... )''',
            'th' : '''Create a table header cell (<th> in html). It is a container. rowspan and colspan are optionnal together.\nUsage : ( "tableid" colnum [ rowspan colspan "sort|nosort" "filter|nofilter" "row|col" "content" ] ... ) TH ( ... )''',
            'td' : '''Create a table cell (<td> in html). It is a container. rowspan and colspan are optionnal together.\nUsage : ( "[ rowspan colspan "content" ] ... ) TD ( ... )''',
            'row' : '''Create a table row (<tr> in html) and put all table cell you want in. It is a container.\nUsage : ( container [ [ rowspan colspan "sort|nosort" "filter|nofilter" "row|col" "content" ] ... ] ... ) ROW ( ... )''',
            'tablerow' : '''Create a simple and empty table row (<tr> in html). It is a container.\nUsage : ( ... ) TABLEROW ( ... )''',
            'tablecell' : '''Create a simple table cell (<td> in html). It is a container.\nUsage : ( "content" ... ) TABLECELL ( ... )''',
            'tablehead' : '''Create a simple table header (<th> in html). It is a container.\nUsage : ( "content" ... ) TABLEHEAD ( ... )''',
            'unorderlist' : '''Create an unordered and empty list (<ul> in html). It is a container.\nUsage : ( "id_attribut" ... ) UNORDERLIST ( ... )''',
            'orderlist' : '''Create an ordered and empty list (<ol> in html). It is a container.\nUsage : ( "id_attribut" ... ) ORDERLIST ( ... )''',
            'listitem' : '''Create a liste item (<li> in html). It is a container.\nUsage : ( "content" ... ) LISTITEM ( ... )''',
            'urlbase' : '''The base URL to use to recompose relative URLs within the document. If this attribute is set, this element must appear before elements whose attributes are URLs. Both absolute and relative URIs are allowed. It is not a container.\nUsage : ( "href_attribut" "target_attribut" ... ) URLBASE ( ... )''',
            'charset' : '''Create a meta charset for document (<meta> in html). The word webreset add automatically a charset meta in head tag. It is not a container.\nUsage : ( "charset_attribut" ... ) CHARSET ( ... )''',
            'httpequiv' : '''Create a meta http-equiv for document (<meta> in html). It is not a container.\nUsage : ( "content_attribut" "htpequiv_attribut" ... ) HTTPEQUIV ( ... )''',
            'meta' : '''Create a meta for document (<meta> in html). It is not a container.\nUsage : ( "content_attribut" "name_attribut" ... ) META ( ... )''',
            'comment' : '''Insert a comment in your html document. Is is not a container.\nUsage : ( "content" .. ) COMMENT ( ... )''',
            'abbr': '''Create an abbreviation tag (<abbr> in html). It is a container.\nUsage : ( "content" "title_attribut" ... ) ABBR ( ... )''',
            'address': '''Create an address tag (<address> in html). It is a container.\nUsage : ( ... ) ADDRESS ( ... )''',
            'area': '''Create an area tag for a map (<area> in html). It is not a container.\nUsage : ( "shape_attribut" "coords_attribut" "href_attribut" ... ) AREA ( ... )''',
            'map': '''Create a map tag (<map> in html). It is a container.\nUsage : ( "name_attribut" ... ) MAP ( ... )''',
            'aside': '''Create an aside tag (<aside> in html). It is a container.\nUsage : ( ... ) ASIDE ( ... )''',
            'audio': '''Create an audio object (<audio> in html). It is a container. this word have 4 parameters : controls, autoplay, loop and muted.\nUsage : ( "controls_attribut" "autoplay_attribut" "inloop_attribut" "muted_attribut" ... ) AUDIO ( ... )''',
            'source': '''Create a source object you can associate to audio or video objects for example (<source> in html). It is not a container.\nUsage : ( "src_attribut" "sourcetype_attribut" ... ) SOURCE ( ... )''',
            'pictsrc': '''Create a souce object for picture. (<source> in html). It is not a container.\nUsage : ( "media_attribut" "srcset_attribut" ... ) PICTSRC ( ... )''',
            'bold': '''Create a bold text tag (<b> in html). It is a container.\nUsage : ( "content" ... ) BOLD ( ... )''',
            'bdo': '''Create a directionnal text (<bdo> in html). It is a container.\nUsage : ( "content" "dir_attribut" ... ) BDO ( ... )''',
            'blockquote': '''Create a blockquote text tag (<blockquote> in html). It is a container.\nUsage : ( "content" ... ) BLOCKQUOTE ( ... )''',
            'canvas': '''Create an area where you can draw with Javascript (<canvas> in html). It is a container.\nUsage : ( "id_attribut" ... ) CANVAS ( ... )''',
            'caption': '''Create a caption for your tables (<caption> in html). It is a container.\nUsage : ( "content" ... ) CAPTION ( ... )''',
            'cite': '''Create a quote (<cite> in html). It is a container.\nUsage : ( "content" ... ) CITE ( ... )''',
            'code': '''Create a text zone where you can put some code (<code> in html). It is a container.\nUsage : ( "content" ... ) CODE ( ... )''',
            'col': '''Defines a column of a table. Mainly used in a colgroup (<col> in html). It is not a container.\nUsage : ( "span_attribut" ... ) COL ( ... )''',
            'colgroup': '''Allows you to define a set of columns in your tables. A 'colgroup' contains 'col' (<colgroup> in html). It is a container.\nUsage : ( ... ) COLGROUP ( ... )''',
            'data': '''This word allows you to associate data with its content (<data> in html). It is a container.\nUsage : ( "content" "value_attribut" ... ) DATA ( ... )''',
            'datalist': '''The 'datalist' contains a set of 'dloption' elements that represent possible values ​​for other controls. It is a container.\nUsage : ( "id_attribut" ... ) DATALIST ( ... )''',
            'dloption': '''A 'dloption' element is contained in a 'datalist (<option> in html). It is not a container.\nUsage : ( "value_attribut" ... ) DLOPTION ( ... )''',
            'dl': '''The 'dl' word represents a description list as a list of pairs associating terms (provided by 'dt' word) and their descriptions or definitions (provided by 'dd' word).\nThis element is used, for example, to implement a glossary. It is a container.\nUsage : ( ... ) DL ( ... )''',
            'dt': '''The 'dt' word identifies a term in a list of definitions or descriptions. This element only appears as a child element of a 'dl' word and is usually followed by a 'dd' word.\nMultiple <dt> elements in succession will indicate that they share the definition/description provided by the next <dd> element. It is a container.\nUsage : ( "content" ... ) DT ( ... )''',
            'dd': '''The 'dd' word provides the description, definition, or value of the preceding term (<dt>) in a description list (<dl>). It is a container.\nUsage : ( "content" ... ) DD ( ... )''',
            'del': '''The 'del' word represents a range of text that has been deleted from a document. This can be used when rendering "track changes" or source code diff information, for example. It is a container\nUsage : ( "content" ... ) DEL ( ... )''',
            'details': '''The 'details' word creates a disclosure widget in which information is visible only when the widget is toggled into an open state.\nA summary or label must be provided using the 'summary' word.\nA disclosure widget is typically presented onscreen using a small triangle that rotates (or twists) to indicate open/closed state, with a label next to the triangle.\nThe contents of the <summary> element are used as the label for the disclosure widget. The contents of the <details> provide the accessible description for the <summary>. It is a container\nUsage : ( "summary_content" "open_attribut" ... ) DETAILS ( ... )''',
            'dfn': '''The 'dfn' word indicates a term to be defined. It is a container.\nUsage : ( "content" ... ) DFN ( ... )''',
            'dialog': '''The 'dialog' word represents a modal or non-modal dialog box or other interactive component, such as a dismissible alert, inspector, or subwindow. It is a container.\nUsage : ( "content" "open_attribut" ... ) DIALOG ( ... )''',
            'em': '''The 'em' word marks text that has stress emphasis. The <em> element can be nested, with each level of nesting indicating a greater degree of emphasis. It is a container\nUsage : ( "content" ... ) EM ( ... )''',
            'fieldset': '''The 'fieldset' word is used to group several controls as well as labels (<label>) within a web form. It is a container.\nUsage : ( "name_attribut" "disabled_attribut" ... ) FIELDSET ( ... )''',
            'figcaption': '''The 'figcaption' word represents a caption or legend describing the rest of the contents of its parent <figure> element, providing the <figure> an accessible name. It is a container.\nUsage : ( "content" ... ) FIGCAPTION ( ... )''',
            'figure': '''The 'figure' word represents self-contained content, potentially with an optional caption, which is specified using the <figcaption> element. The figure, its caption, and its contents are referenced as a single unit. It is a container.\nUsage : ( ... ) FIGURE ( ... )''',
            'form': '''The 'form' word represents a document section containing interactive controls for submitting information.It is a container.\nUsage : ( "action_attribut" "method_attribut" ... ) FORM ( ... )''',
            'hr': '''The 'hr' word represents a thematic break between paragraph-level elements. It is not a container.\nUsage : ( ... ) HR ( ... )''',
            'italic': '''The 'italic' word represents a range of text that is set off from the normal text for some reason, such as idiomatic text, technical terms, taxonomical designations, among others. It is a container.\nUsage : ( "content" ... ) ITALIC ( ... )''',
            'iframe': '''The 'iframe' word represents a nested browsing context, embedding another HTML page into the current one. It is a container.\nUsage : ( "src_attribut" ... ) IFRAME ( ... )''',
            'ins': '''The 'ins' word represents a range of text that has been added to a document. It is a container.\nUsage : ( "content" ... ) INS ( ... )''',
            'kbd': '''The 'kbd' word represents a span of inline text denoting textual user input from a keyboard, voice input, or any other text entry device. It is a container.\nUsage : ( "content" ... ) KBD ( ... )''',
            'legend': '''The 'legend' word represents a caption for the content of its parent <fieldset>. It is a container.\nUsage : ( "content" ... ) LEGEND ( ... )''',
            'main': '''The 'main' word represents the dominant content of the <body> of a document.\nThe main content area consists of content that is directly related to or expands upon the central topic of a document, or the central functionality of an application.. It is a container.\nUsage : ( ... ) MAIN ( ... )''',
            'mark': '''The 'mark' word represents text which is marked or highlighted for reference or notation purposes due to the marked passage's relevance in the enclosing context. It is a container.\nUsage : ( "content" ... ) MARK ( ... )''',
            'menu': '''The 'menu' word represents an unordered list of items (which are represented by <li> elements). It is a container.\nUsage : ( ... ) MENU ( ... )''',
            'meter': '''The 'meter' word represents either a scalar value within a known range or a fractional value. It is a container.\nUsage : ( "content" "max_attribut" "min_attribut" "value_attribut" "id_attribut" ... ) METER ( ... )''',
            'nav': '''The 'nav' word represents a section of a page whose purpose is to provide navigation links, either within the current document or to other documents. It is a container.\nUsage : ( ... ) NAV ( ... )''',
            'noscript': '''The 'noscript' word defines a section of HTML to be inserted if a script type on the page is unsupported or if scripting is currently turned off in the browser. It is a container.\nUsage : ( "content" ... ) NOSCRIPT ( ... )''',
            'optgroup': '''The 'optgroup' word creates a grouping of options within a <select> HTML element. It is a container.\nUsage : ( "disabled_attribut" "label_attribut" ... ) OPTGROUP ( ... )''',
            'picture': '''The 'picture' word represents an HTML element <picture> that contains zero or more <source> elements ('pictsrc' word) and one <img> element ('img' word) to offer alternative versions of an image for different display/device scenarios. It is a container.\nUsage : ( ... ) PICTURE ( ... )''',
            'pre': '''The 'pre' word represents preformatted text which is to be presented exactly as written in the HTML file. It is a container.\nUsage : ( "content" ... ) PRE ( ... )''',
            'quote': '''The 'quote' word (<q> in html) indicates that the enclosed text is a short inline quotation. It is a container.\nUsage : ( "content" ... ) QUOTE ( ... )''',
            'section': '''The 'section' word represents a generic standalone section of a document, which doesn't have a more specific semantic element to represent it. It is a container.\nUsage : ( ... ) SECTION ( ... )''',
            'sub': '''The 'sub' word specifies inline text which is to be displayed as subscript for solely typographical reasons. It is a container.\nUsage : ( "content" ... ) SUB ( ... )''',
            'summary': '''The 'summary' word specifies a summary, caption, or legend for a <details> HTML element's disclosure box. It is a container.\nUsage : ( "content" ... ) SUMMARY ( ... )''',
            'sup': '''The 'sup' word specifies inline text which is to be displayed as superscript for solely typographical reasons. It is a container.\nUsage : ( "content" ... ) SUP ( ... )''',
            'svg': '''''',
            'svgrect': '''''',
            'svgpolygon': '''''',
            'svgellipse': '''''',
            'svgcircle': '''''',
            'svgline': '''''',
            'svgpolyline': '''''',
            'svgpath': '''''',
            'svgtext': '''''',
            'svgtextpath': '''''',
            'svgimage': '''''',
            'svgmarker': '''''',
            'svglineargradient': '''''',
            'svgradialgradient': '''''',
            'svgpattern': '''''',
            'video': '''The 'video' word embeds a media player which supports video playback into the document. It is a container.\nUsage : ( "controls_attribut" "autoplay_attribut" "inloop_attribut" "muted_attribut" ... ) VIDEO ( ... )''',
            'layoutgrid' : '''''',
            'layoutarea' : '''''',
            'layout' : '''''',
            'savelaystyle' : '''''',
            'grouplaystyle' : '''''',
            'posted' : '''''',
            'redirect' : '''''',
            'htmlcontent' : '''''',
            'session' : '''''',
            'getsession' : '''''',
            'setsessvar' : '''''',
            'getsessvar' : '''''',
            'session?' : '''''',
            'setsessduration' : '''''',
            'sessduration?' : '''''',
            'completeselect' : '''''',
            'card' : '''''',
            'addcardtitle' : '''''',
            'addcardbody' : '''''',
            'addcardbottom' : '''''',
            'flipcard' : '''''',
            'profilecard' : '''''',
            'productcard' : '''''',
            'splitter' : '''''',
            'divider' : '''''',
            'overlay' : '''''',
            'tab' : '''''',
            'accordion' : '''''',
            'sidenav' : '''''',
            'topnav' : '''''',
            'filteredlist' : '''''',
            'modal' : '''''',
            'advancebutton' : ''''''
        }